= ORKG REST API Documentation
:doctype: book
:toc: right
:icons: font

// Non-document attributes
include::../_default-attributes.adoc[]
:pagination_note: This is a paginated, and sortable call, check the table below for allowed keys for sorting <<sorting-and-pagination>>.

[[overview]]
== Overview

This document describes the REST API of the {orkg}.

WARNING: This API is still **in development** and therefore **unstable** and **subject to change**!
         Be aware that the API can (and will) break without notice, so beware if you intend to consume it directly.
         We will support a stable API in the future, but it is uncertain when that will be.
         This documentation will be updated to reflect that.

////
=== Current version
=== Schema
=== Authentication
=== Parameters
=== Root endpoint
=== Client errors
=== HTTP redirects
////

[[overview-http-verbs]]
=== HTTP verbs

The {orkg} REST API tries to adhere as closely as possible to standard
 HTTP and REST conventions in its use of HTTP verbs.
|===
| Verb | Usage

| `GET`
| Used to retrieve a resource

| `POST`
| Used to create a new resource
|===

The verbs `PATCH`, `PUT`, and `DELETE` are (currently) unsupported.
////
| `PATCH`
| Used to update an existing resource, including partial updates

| `PUT`
| Used to update an existing resource, full updates only

| `DELETE`
| Used to delete an existing resource
|===
////

[[overview-http-status-codes]]
=== HTTP status codes
The {orkg} REST API tries to adhere as closely as possible to standard
 HTTP and REST conventions in its use of HTTP status codes.

|===
| Status code | Usage

| `200 OK`
| Standard response for successful HTTP requests.
The actual response will depend on the request method used.
In a `GET` request, the response will contain an entity corresponding to the requested resource.
In a `POST` request, the response will contain an entity describing or containing the result of the action.

| `201 Created`
| The request has been fulfilled and resulted in a new resource being created.

| `204 No Content`
| The server successfully processed the request, but is not returning any content.

| `400 Bad Request`
| The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).

| `404 Not Found`
| The requested resource could not be found but may be available again in the future. Subsequent requests by the client are permissible.
|===

All responses with error codes that do not indicate success will contain a payload that describes the error.
Their structure is documented in the section about <<error-represenation,Error representation>>.

////
=== Hypermedia
=== Pagination
=== Conditional requests
=== Cross origin resource sharing
////

[[authentication]]
include::parts/auth.adoc[leveloffset=+1]

[[statements]]
== Statements

A statement represents a kind of sentence in the knowledge graph,
 similar to RDF triples.
Similar to a real sentence, it is a tuple of a subject, a predicate, and
 an object.

Subjects and objects represent nodes in the graph are formed from a
 <<Resources,resource>>.
Objects can also be a <<Literals,literal value>>.

<<Predicates>> represent edges (relationships) in the graph.

Resources and predicates are identifiable by an ID, whereas literals are
 not since they represent a value.

Statements can also be referenced by their IDs.
This allows storing and retrieving provenance information about them.

[[statements-list]]
=== Listing statements

A `GET` request lists all the statements:

operation::statement-controller-integration-test-index[snippets='curl-request,http-response']

TIP: {pagination_note}

[[statements-create]]
=== Creating statements
A `POST` request creates a new statement.
The response will be `201 Created` when successful.
The statement can be retrieved by following the URI in the `Location` header field.

NOTE: The response body contains the created statement for convenience. This might be subject to change.

Creating statements can be done in two ways:

1. For objects of type resource, send three IDs.
2. For objects of type literal, send two IDs and the literal value in the body.

[[statements-create-objects-resource]]
==== Creating statements with resource objects

Create a statement by submitting three IDs via `POST`:

operation::statement-controller-integration-test-add-with-resource[snippets='curl-request,http-response']

[[statements-delete]]
=== Deleting a statement
Delete a statement by providing the ID of the statement via a `DELETE` call:

The response will be `204 No Content` when successful.

operation::statements-delete-literal-statement_is-no-content[snippets='curl-request,http-response']

[[statements-fetch]]
=== Fetching a statement

A `GET` request provides information about a statement.

operation::statement-controller-integration-test-fetch[snippets='curl-request,http-response']

[[statements-lookup-by-subject]]
=== Lookup statements by subject

A `GET` request lists all the statements with a given subject:

operation::statement-controller-integration-test-lookup-by-subject[snippets='curl-request,http-response']

TIP: {pagination_note}

[[statements-lookup-by-predicate]]
=== Lookup statements by predicate

A `GET` request lists all the statements with a given predicate:

operation::statement-controller-integration-test-lookup-by-predicate[snippets='curl-request,http-response']

TIP: {pagination_note}

[[statements-fetch-as-bundle]]
=== Fetching statements for a thing as a bundle

A `GET` request that fetches the entire subgraph of a certain entity and returns all the statements as a bundle.

A `Bundle` is a collection of statements that represents the sub-graph starting from a certain `Thing` in the KG.

When fetching a bundle of statements, filtering is possible via specifying certain parameters in the request.
The number of levels in the tree being fetched can be filtered using the two query parameters `minLevel` & `minLevel`.
Furthermore, to be able to further control which statements to fetch, a black/white listing operation can be introduced via the query parameters `blacklist` & `whitelist` - this filter applies to classes of subjects and objects of statements only -

The endpoint also provide the parameter `includeFirst` which by default is `True` meaning it will not apply black/white listing on first level.

operation::statement-controller-integration-test-fetch-bundle[snippets='curl-request,http-response']

include::parts/bulk-statements.adoc[]

include::parts/classes.adoc[]

[[resources]]
== Resources

Resources represent nodes in the knowledge graph.
They can appear in the subject or object position in <<Statements,statements>>.

[[resources-list]]
=== Listing resources

A `GET` request lists all resources:

operation::resource-controller-integration-test-index[snippets='request-parameters,curl-request,http-response']

TIP: {pagination_note}

[[resources-create]]
=== Creating resources

A `POST` request creates a new resource with a given label.
An optional set of classes can be provided.
The response will be `201 Created` when successful.
The resource can be retrieved by following the URI in the `Location` header field.

NOTE: The created resource is returned in the body for convenience. This might be subject to change.

operation::resource-controller-integration-test-add[snippets='request-fields,curl-request,http-response']

The response body consists of the following fields:

operation::resource-controller-integration-test-add[snippets='response-fields']

[[resources-edit]]
=== Editing a resource

A `PUT` request updates a resource with a new given label.
The response will be `200 OK` when successful.
The created resource is returned in the body for convenience.

operation::resource-controller-integration-test-edit[snippets='request-fields,curl-request,http-response']

[[resources-fetch]]
=== Fetching a resource

A `GET` request provides information about a resource.

operation::resource-controller-integration-test-fetch[snippets='curl-request,http-response']

[[resources-lookup]]
=== Lookup a resource by label

Resources can be looked up by label by providing a search fragment.

operation::resource-controller-integration-test-lookup[snippets='request-parameters,curl-request,http-response']

TIP: {pagination_note}


[[resources-delete]]
=== Delete a resource

A `DELETE` request with the id of the resource to delete.

Note: This request is only acceptable if you have sufficient permissions.

a successful request return a No-Content HTTP status code.

operation::resource-controller-integration-test-delete-resource-success[snippets='curl-request,http-response']

If the resource doesn't exist, the API returns a 404 status code.

operation::resource-controller-integration-test-delete-resource-not-found[snippets='curl-request,http-response']

To safely delete a resource, the resource shouldn't have any statements related to it. In this case a Forbidden HTTP status is returned.

operation::resource-controller-integration-test-delete-resource-forbidden[snippets='curl-request,http-response']

[[predicates]]
== Predicates

Predicates represent edges (relationships between nodes) in the
 knowledge graph.
They consist of an ID and a label (for presentation).
IDs always start with "P", followed by a number.

[[predicates-list]]
=== Listing predicates

A `GET` request lists all predicates:

operation::predicate-controller-test-index[snippets='request-parameters,curl-request,http-response']

TIP: {pagination_note}

[[predicates-create]]
=== Creating predicates

A `POST` request creates a new predicate with a given label.
The response will be `201 Created` when successful.
The predicate can be retrieved by following the URI in the `Location` header field.

NOTE: The response body contains the created predicate for convenience. This might be subject to change.

operation::predicate-controller-test-add[snippets='request-fields,curl-request,http-response']

The response body consists of the following fields:

operation::predicate-controller-test-add[snippets='response-fields']

[[predicates-edit]]
=== Editing a predicate

A `PUT` request updates a predicate with a new given label.
The response will be `200 OK` when successful.
The created predicate is returned in the body for convenience.

operation::predicate-controller-test-edit[snippets='curl-request,http-response']

[[predicates-fetch]]
=== Fetching a predicate

A `GET` request provides information about a predicate.

operation::predicate-controller-test-fetch[snippets='curl-request,http-response']

[[predicates-lookup]]
=== Lookup a predicate by label

Predicates can be looked up by label by providing a search fragment.

operation::predicate-controller-test-lookup[snippets='curl-request,http-response']


[[literals]]
== Literals

Literals represent nodes in the knowledge graph.
They can appear in the object position in <<Statements,statements>>.

[[literals-list]]
=== Listing Literals

A `GET` request returns a <<sorting-and-pagination,paged>> list of literals.
If no paging request parameters are provided, the default values will be used.

operation::literals-get-paged[snippets='curl-request,http-response']

[[literals-create]]
=== Creating Literals

A `POST` request creates a new literal with a given label (its value).
The response will be `201 Created` when successful.
The resource can be retrieved by following the URI in the `Location` header field.

NOTE: The created literal is returned in the body for convenience. This might be subject to change.

operation::literal-controller-integration-test-add[snippets='request-fields,curl-request,http-response']

The response body consists of the following fields:

operation::literal-controller-integration-test-add[snippets='response-fields']

[[literals-edit]]
=== Editing a literal

A `PUT` request updates a literal with a new value through the label property.
The response will be `200 OK` when successful.
The created literal is returned in the body for convenience.

operation::literal-controller-integration-test-edit[snippets='curl-request,http-response']

[[literals-fetch]]
=== Fetching a literal

A `GET` request provides information about a <<literal-represenation,literal>>.

operation::literals-get-single[snippets='curl-request,http-response']

[[literals-lookup]]
=== Lookup a literal by label

Literals can be looked up by label by providing a search fragment.

operation::literal-controller-integration-test-lookup[snippets='curl-request,http-response']

include::parts/lists.adoc[]

[[papers]]
include::parts/papers.adoc[]

[[contributions]]
include::parts/contributions.adoc[]

[[comparisons]]
include::parts/comparisons.adoc[leveloffset=+1]

[[visualizations]]
include::parts/visualizations.adoc[leveloffset=+1]

[[templates]]
include::parts/templates.adoc[leveloffset=+1]

[[rdf-integration]]
include::parts/rdf.adoc[leveloffset=+1]

[[contributors]]
include::parts/contributors.adoc[leveloffset=+1]

include::parts/organizations.adoc[]

include::parts/observatories.adoc[]

include::parts/problems.adoc[]

include::parts/research-fields.adoc[]

include::parts/datasets-benchmarks.adoc[]

[[reproducibility-score]]
== Reproducibility Score
The reproducibility score measures the availability, accessibility, linkability, and license of a resource.

include::parts/licenses.adoc[]

[[widget]]
include::parts/widget.adoc[leveloffset=+1]

include::parts/identifiers.adoc[leveloffset=+1]

[[sorting-and-pagination]]
== Sorting and Pagination

For all request that lists entities, pagination and sorting are applied automatically.
The attributes of paged responses are described in the section about <<page-representation, Page representations>>.

Endpoints supporting paging all take the following (optional) request parameters:

[cols="1,3"]
include::{snippets}/paged-page/request-parameters.adoc[]

An example of a response of a paged list looks like this:

include::{snippets}/paged-page/response-body.adoc[]

NOTE: The elements in `content` can be objects of arbitrary structure and are sorted according to the request parameters, if the endpoint supports it.

By default, sorting is done by the `created_at` property (time-based).

[cols="e,m"]
.Sorting keys allowed by the API
[options="header"]
|=======================
|Key  |Description
2+^|*For sorting resources & predicates*
|id   | the id of the resource or predicate
|label    | the label of the resource or the predicate
|created    |the datetime timestamp of the creation
2+^|*For sorting statements*
|id   | the statement id
|created    |the datetime timestamp of the creation
|sub.label    |the label of the subject
|sub.created  |the creation timestamp of the subject
|rel.label    |the label of the predicate
|rel.created  |the creation timestamp of the predicate
|obj.label    |the label of the object
|obj.created  |the creation timestamp of the object
|=======================


== Representations

This section contains the _resource definitions_ (also called _representations_) of the entities of this API.

=== Basic Types

[[timestamp-representation]]
==== Timestamps

All timestamps used in this API are in https://wikipedia.org/wiki/ISO_8601[ISO 8601] format.
Although nanosecond precision is available currently, clients MUST NOT rely on it, as it might be subject to change.

[[error-represenation]]
=== Errors

[cols="1,1,3"]
include::{snippets}/errors-simple-message-exception/response-fields.adoc[]

[[page-representation]]
=== Pages

[cols="1,1,3"]
include::{snippets}/paged-page/response-fields.adoc[]

=== Entities

[[literal-represenation]]
==== Literal

[cols="1,1,3"]
include::{snippets}/literals-get-single/response-fields.adoc[]
