= Classes

Classes represent concepts in the knowledge graph.
They can be attached to <<Resources,resources>> to indicate that the resource belongs to the respective class.

[[classes-fetch]]
== Fetching Classes

The Open Research Knowledge Graph REST API provides two methods for fetching individual classes.

[[classes-fetch-by-id]]
=== Fetching Classes by ID

A `GET` request provides information about a class by ID.

operation::classes_get-single[snippets='path-parameters,curl-request,http-response,response-fields']

[[classes-fetch-by-uri]]
=== Fetching Classes by URI

A `GET` request provides information about a class by URI.

operation::classes_get-single-by-uri[snippets='query-parameters,curl-request,http-response,response-fields']

[[classes-list]]
== Listing Classes

A `GET` request returns a <<sorting-and-pagination,paged>> list of <<classes-fetch,classes>>.
If no paging request parameters are provided, the default values will be used.

operation::classes_get-paged[snippets='curl-request']

The following list of request parameters are supported:

operation::classes_get-paged-with-parameters[snippets='query-parameters,curl-request']

[[classes-create]]
== Creating Classes

A `POST` request creates a new class with a given label.
An optional URI can be given to link to the class in an external ontology (RDF).
The response will be `201 Created` when successful.
The class can be retrieved by following the URI in the `Location` header field.

operation::classes_create[snippets='request-fields,curl-request,response-headers,http-response']

[[classes-edit]]
== Updating Classes

The Open Research Knowledge Graph REST API provides two endpoints for updating classes.

[[classes-update]]
=== Updating Classes (PATCH)

A `PATCH` request updates a class with a new given label and URI.
Only fields provided in the request, and therefore non-null, will be updated.
The response will be `204 NO CONTENT` when successful.

operation::classes_update[snippets='path-parameters,request-fields,curl-request,response-headers,http-response']

[[classes-replace]]
=== Updating Classes (PUT)

A `PUT` request updates a class with a new given label and URI.
All fields will be updated in the process.
The response will be `204 NO CONTENT` when successful.

operation::classes_replace[snippets='path-parameters,request-fields,curl-request,response-headers,http-response']

[[class-hierarchies]]
include::class-hierarchies.adoc[leveloffset=+1]

[[classes-import]]
== Importing Classes

The {orkg} REST API provides two endpoints for importing classes from external ontologies.

[[classes-import-by-uri]]
=== Importing Classes by URI

A `POST` request imports a class from an external ontology by a given URI.
The response will be `201 Created` when successful, even when the class was already imported.

operation::import_import-class-by-uri[snippets='request-fields,curl-request,response-headers,http-response']

[[classes-import-by-short-form]]
=== Importing Classes by Short Form

A `POST` request imports a class from an external ontology by a given short form id.
The response will be `201 Created` when successful, even when the class was already imported.

operation::import_import-class-by-short-form[snippets='request-fields,curl-request,response-headers,http-response']
