= Lists

Lists represent an ordered collection of statements in the knowledge graph.
Their elements are defined by <<statements,statement>> using the "has list element" predicate and a special "index" property, indicating the position in the list.
The elements of a list can only be modified using the dedicated list endpoints.

[[list-fetch]]
== Fetching Lists

A `GET` request provides information about a list.

operation::lists-get-single[snippets='path-parameters,curl-request,http-response,response-fields']

[[list-elements]]
== Fetching List Elements

A `GET` request returns a <<sorting-and-pagination,paged>> list of elements, in order, with their full representations (see <<resources,resources>>, <<classes,classes>>, <<predicates,predicates>>, <<literals,literals>>), that are part of the list.
If no paging request parameters are provided, the default values will be used.

operation::lists-get-elements[snippets='path-parameters,curl-request,http-response']

[[lists-create]]
== Creating Lists

A `POST` request creates a new list with all the given parameters.
The response will be `201 Created` when successful.
The list resource (object) can be retrieved by following the URI in the `Location` header field.

operation::lists-create[snippets='request-fields,curl-request,response-headers,http-response']

[[lists-update]]
== Updating Lists

A `PATCH` request updates a list with all the given parameters.
The response will be `204 No Content` when successful.

operation::lists-update[snippets='path-parameters,request-fields,curl-request,response-headers,http-response']
