= ORKG REST API Documentation
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: right

:orkg: Open Research Knowledge Graph

== Overview

This document describes the REST API of the {orkg}.

////
=== Current version
=== Schema
=== Authentication
=== Parameters
=== Root endpoint
=== Client errors
=== HTTP redirects
=== HTTP verbs
=== Hypermedia
=== Pagination
=== Conditional requests
=== Cross origin resource sharing
////

== Statements

=== Introduction to statements

A statement represents a kind of sentence in the knowledge graph,
 similar to RDF triples.
Similar to a real sentence, it is a tuple of a subject, a predicate, and
 a object.

Subjects and objects represent nodes in the graph are formed from a
 <<Resources,resource>>.
Objects can also be a literal value.

<<Predicates>> represent edges (relationships) in the graph.

Resources and predicates are identifiable by an ID, whereas literals are
 not since they represent a value.

=== Listing statements

A `GET` request lists all the statements:

operation::statement-controller-test-index[snippets='curl-request,response-body']

== Resources

Resources represent nodes in the knowledge graph.
They can appear in the subject or object position in <<Statements,statements>>.

=== Listing resources

A `GET` request lists all resources:

operation::resource-controller-test-index[snippets='curl-request,response-body']

=== Creating resources

A `POST` request creates a new resource with a given label.

operation::resource-controller-test-add[snippets='request-fields,curl-request,response-body']

The response body consists of the following fields:

operation::resource-controller-test-add[snippets='response-fields']

== Predicates

Predicates represent edges (relationships between nodes) in the
 knowledge graph.
They consist of an ID and a label (for presentation).
IDs always start with "P", followed by a number.

=== Listing predicates

A `GET` request lists all predicates:

operation::predicate-controller-test-index[snippets='curl-request,response-body']

=== Creating predicates

A `POST` request creates a new predicate with a given label.

operation::predicate-controller-test-add[snippets='request-fields,curl-request,response-body']

The response body consists of the following fields:

operation::predicate-controller-test-add[snippets='response-fields']
