= Research Fields

Research fields are meta objects that help better classify the content within the ORKG.
The research field is essentially a <<Resources,resource>> and hence inherits all the specifications of resource.

NOTE: In the following sections, the response fields of the page object are omitted for brevity.

== Research Fields and Research Problems

[[research-fields-list-research-problems]]
=== Listing Research Problems of Research Fields

A `GET` request returns a <<sorting-and-pagination,paged>> list of all research problem <<resources,resources>> belonging to a given research field.
The endpoint supports <<visibility-filtering-legacy>>.

operation::research-fields-get-problems-per-field[snippets='path-parameters,curl-request']

[[research-fields-list-research-problems-with-subfields]]
=== Listing Research Problems of Research Fields and their Subfields

A `GET` request to `/api/research-fields/{id}/subfields/research-problems` returns a <<sorting-and-pagination,paged>> list of research problem <<resources,resources>> belonging to a given research field and its subfields.

All path and request parameters are exactly the same as on the <<research-fields-list-research-problems,endpoint without subfields>>.


== Research Fields and Contributors

[[research-fields-list-contributors]]
=== Listing Contributors of Research Fields

A `GET` request returns a <<sorting-and-pagination,paged>> list of <<contributors,contributors>> that contributed to a given research field.

WARNING: This endpoint does *not* support <<visibility-filter,visibility filtering>>!
         The only supported path parameter is `featured`.

operation::research-fields-get-contributors-per-field[snippets='path-parameters,curl-request']

[[research-fields-list-contributors-with-subfields]]
=== Listing Contributors of Research Fields and their Subfields

A `GET` request to `/api/research-fields/{id}/subfields/contributors` returns a <<sorting-and-pagination,paged>> list of contributors that contributed to a given research field and its subfields.
All path and request parameters are exactly the same as on the <<research-fields-list-contributors,endpoint without subfields>>.


[[research-fields-list-children]]
== Listing Subfields

A `GET` request returns a <<sorting-and-pagination,paged>> list of all sub research field <<resources,resources>> for a given research field.

operation::research-fields-find-children[snippets='path-parameters,curl-request']

include::{snippets}/research-fields-research-field-with-child-count/response-fields.adoc[]

[[research-fields-list-parents]]
== Listing Parent Research Fields

A `GET` request returns a <<sorting-and-pagination,paged>> list of all parent research field <<resources,resources>> for a given research field.

operation::research-fields-find-parents[snippets='path-parameters,curl-request']

[[research-fields-list-roots]]
== Listing Root Research Fields of Subfields

A `GET` request returns a <<sorting-and-pagination,paged>> list of all root research field <<resources,resources>> for a given research field.

operation::research-fields-find-roots[snippets='path-parameters,curl-request']

[[research-fields-list-all-roots]]
== Listing all Root Research Fields

A `GET` request returns a <<sorting-and-pagination,paged>> list of all root research field <<resources,resources>>.

operation::research-fields-find-all-roots[snippets='curl-request']

[[research-fields-list-hierarchy]]
== Listing Research Fields Hierarchy

A `GET` request returns a <<sorting-and-pagination,paged>> list of all paths from each root research field <<resources,resource>> to the given research field.

operation::research-fields-find-hierarchy[snippets='path-parameters,curl-request,http-response']

include::{snippets}/research-fields-research-field-hierarchy-entry/response-fields.adoc[]
