repos:
  # TODO: re-enable original repository when changes are included
  #- repo: https://github.com/jguttman94/pre-commit-gradle
  #  rev: v0.2.1
  - repo: https://github.com/manuelprinz/pre-commit-gradle
    rev: spotless-target
    hooks:
      - id: gradle-spotless
        args:
          - '--wrapper'
