version: '3.7'

services:

  api:
    image: registry.gitlab.com/tibhannover/orkg/orkg-backend
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgres/postgres'
      SPRING_DATA_NEO4J_URI: 'bolt://neo4j:7687'
    ports:
      - '127.0.0.1:8080:8080'
      #- '::1:8080:8080'
    networks:
      - backend
    depends_on:
      - neo4j
      - postgres

  neo4j:
    image: neo4j:4.2-community
    ports:
      - '127.0.0.1:7474:7474' # HTTP
      #- '::1:7474:7474'
      - '127.0.0.1:7687:7687' # BOLT
      #- '::1:7687:7687'
    environment:
      NEO4JLABS_PLUGINS: '["apoc"]'
      NEO4J_AUTH: none
      #NEO4J_dbms_memory_heap_max__size: 1G
      #NEO4J_dbms_memory_pagecache_size: 512M
    networks:
      - backend
    volumes:
      - 'neo4j-data:/data'

  postgres:
    image: postgres:11
    expose:
      - '5432'
    ports:
      - '127.0.0.1:5432:5432'
      #- '::1:5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - backend
    volumes:
      - 'postgres-data:/var/lib/postgresql/data/pgdata'

  keycloak:
    image: quay.io/keycloak/keycloak:13.0.1
    ports:
      - 127.0.0.1:8888:8080  # Port re-mapped to prevent conflict with API
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: H2
    networks:
      - backend

  # Mail server. Can be used in Keycloak to test mail flows.
  mailhog:
    image: mailhog/mailhog
    ports:
      - 127.0.0.1:1025:1025  # SMTP
      - 127.0.0.1:8025:8025  # User interface
    networks:
      - backend

networks:
  backend:

volumes:
  neo4j-data:
  postgres-data:
