version: '3'

services:

  prototype:
    image: orkg/prototype
    ports:
      - '8000:8000'
    networks:
      - backend
    depends_on:
      - neo4j

  neo4j:
    image: orkg/neo4j-dev
    ports:
      - '7474:7474' # HTTP
      - '7687:7687' # BOLT
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_unmanagedExtensionClasses=semantics.extension=/rdf
      - NEO4J_dbms_memory_heap_max__size=8G
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    networks:
      - backend
    volumes:
      - 'neo4j-data:/data'

  postgres:
    image: postgres:11
    ports:
      - '5432:5432'
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - backend
    volumes:
      - 'postgres-data:/var/lib/postgresql/data/pgdata'

networks:
  backend:

volumes:
  neo4j-data:
  postgres-data:
