version: '3'

services:

  prototype:
    image: orkg/prototype
    ports:
      - '8000:8000'
    networks:
      - backend
    depends_on:
      - neo4j

  neo4j:
    image: orkg/neo4j-dev
    ports:
      - '7474:7474' # HTTP
      - '7687:7687' # BOLT
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_unmanagedExtensionClasses=semantics.extension=/rdf
    networks:
      - backend
    volumes:
      - 'neo4j-data:/data'

networks:
  backend:

volumes:
  neo4j-data:
