version: '3.7'

services:

  api:
    image: registry.gitlab.com/tibhannover/orkg/orkg-backend
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgres/postgres'
      SPRING_DATA_NEO4J_URI: 'bolt://neo4j:7687'
    ports:
      - '127.0.0.1:8080:8080'
      - '::1:8080:8080'
    networks:
      - backend
    depends_on:
      - neo4j
      - postgres

  neo4j:
    image: neo4j:3.5
    expose:
      - '7687' # BOLT
    ports:
      - '127.0.0.1:7474:7474' # HTTP
      - '::1:7474:7474'
    environment:
      NEO4JLABS_PLUGINS: '["apoc"]'
      NEO4J_AUTH: none
      NEO4J_dbms_memory_heap_max__size: 8G
    networks:
      - backend
    volumes:
      - 'neo4j-data:/data'

  postgres:
    image: postgres:11
    expose:
      - '5432'
    ports:
      - '127.0.0.1:5432:5432'
      - '::1:5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - backend
    volumes:
      - 'postgres-data:/var/lib/postgresql/data/pgdata'

networks:
  backend:

volumes:
  neo4j-data:
  postgres-data:
