version: '3'

services:

  api:
    image: registry.gitlab.com/tibhannover/orkg/orkg-backend
    ports:
      - '8000:8000'
    networks:
      - backend
    depends_on:
      - neo4j
      - postgres

  neo4j:
    image: neo4j:3.5
    ports:
      - '7474:7474' # HTTP
      - '7687:7687' # BOLT
    environment:
      NEO4JLABS_PLUGINS: '["apoc"]'
      NEO4J_AUTH: none
      NEO4J_dbms_memory_heap_max__size: 8G
    networks:
      - backend
    volumes:
      - 'neo4j-data:/data'

  postgres:
    image: postgres:11
    ports:
      - '5432:5432'
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - backend
    volumes:
      - 'postgres-data:/var/lib/postgresql/data/pgdata'

networks:
  backend:

volumes:
  neo4j-data:
  postgres-data:
