= ORKG Backend Prototype
Manuel Prinz <manuel.prinz@tib.eu>

:icons: font

This repository contains a backend prototype for the ORKG based on the Spring Framework.
It is written in Kotlin as a proof-of-concept and for experimenting with a possible architecture and technologies.

== Building and running

To build and run the prototype, type:

    ./gradlew bootRun

This will start a server running on http://localhost:8080.
The only available REST resource (for now) is http://localhost:8080/api/articles/.

This also requires a Blazegraph server running on http://localhost:8889/bigdata/.
It expects the SumSur ontology to be loaded into the triple-store.
See the `orkg-backend` and `orkg-ontology`repository for instructions.

== Building Docker images

To build all Docker images (that contain the service dependencies), run:

    ./gradlew docker

If you want to build only specific images, either

[loweralpha]
. call `./gradlew :docker/IMAGE:docker` from the project root directory, or
. go to a `docker/IMAGE` directory and call `../../gradlew docker` there,

where `IMAGE` is the name of a sub-directory under `docker/`.

== Features

Not much, to be honest. Particularly,

* a single REST resource, and
* a repository that queries a Blazegraph server using SPARQL.

An implementation of the `ArticleRepository` for Blazegraph is underway.
One for Neo4j will follow.
(The idea is to explore how to implement vendor-independent data models and a clean architecture.)

== TODOs

- [ ] Add tests!
- [x] Add connector to Blazegraph (SPARQL)
- [ ] Add connector to Blazegraph (native)
- [ ] Add connector to Neo4j
- [ ] Add proper documentation
- [ ] Add CI configuration
- [ ] Perform write operations in the repository
