spring:
  application:
    name: orkg-backend
  profiles:
    active: development
  # Get rid of "org.postgresql.jdbc.PgConnection.createClob() not implemented" error, see
  # https://hibernate.atlassian.net/browse/HHH-12368
  jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true
  rdf:
    # Vocab prefix not used, still hard coded
    # might need to be copied to other profiles on deployment
    vocab-prefix: 'http://orkg.org/orkg'
    frontend-uri: 'http://localhost:3000'
orkg:
  storage:
    images:
      dir: "${user.dir}/images"
  init:
    setup:
      entities-file: "data/required_entities.json"
  datacite:
    username: ""
    password: ""
    doiPrefix: "10.7484"
    url: "https://api.test.datacite.org/dois"
    publish: "draft"
---
spring:
  profiles: development
  data:
    neo4j:
      uri: 'bolt://localhost:7687'
      #auto-index: validate
      use-native-types: true
  datasource:
    url: 'jdbc:postgresql://localhost/postgres'
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    # generate-ddl: true
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.neo4j.ogm.drivers.bolt.request.BoltRequest: DEBUG
keycloak:
  realm: myrealm
  auth-server-url: http://localhost:8180/auth/
  ssl-required: external
  resource: react-test-app
  use-resource-role-mappings: true
  principal-attribute: preferred_username
  public-client: true
  bearer-only: true
  autodetect-bearer-only: true

app:
  cors:
    allowed-origins: http://localhost:3000

springdoc:
  show-actuator: true
  swagger-ui:
    groups-order: DESC
