server:
  port: 8000
spring:
  profiles:
    active: development
  # Get rid of "org.postgresql.jdbc.PgConnection.createClob() not implemented" error, see
  # https://hibernate.atlassian.net/browse/HHH-12368
  jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true
---
spring:
  profiles: development
  data:
    neo4j:
      uri: 'bolt://localhost:7687'
      #auto-index: validate
  datasource:
    url: 'jdbc:postgresql://localhost/postgres'
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    # generate-ddl: true
---
spring:
  profiles: docker
  data:
    neo4j:
      uri: 'bolt://neo4j:7687'
      #username:
      #password:
