server:
  port: 8000
spring:
  profiles:
    active: development
---
spring:
  profiles: development
  data:
    neo4j:
      uri: 'bolt://localhost:7687'
      #auto-index: validate
---
spring:
  profiles: docker
  data:
    neo4j:
      uri: 'bolt://neo4j:7687'
      #username:
      #password:
---
spring:
  profiles: testing
  data:
    neo4j:
      embedded:
        enabled: true
