spring:
  profiles:
    active: development
  # Get rid of "org.postgresql.jdbc.PgConnection.createClob() not implemented" error, see
  # https://hibernate.atlassian.net/browse/HHH-12368
  jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true
  rdf:
    # Vocab prefix not used, still hard coded
    # might need to be copied to other profiles on deployment
    vocab-prefix: 'http://orkg.org/orkg'
    frontend-uri: 'http://localhost:3000'
orkg:
  storage:
    images:
      dir: "${user.dir}/images"
  init:
    setup:
      entities-file: "data/required_entities.json"
  datacite:
    username: ""
    password: ""
    doiPrefix: "10.7484"
    url: "https://api.test.datacite.org/dois"
    publish: "draft"
---
spring:
  profiles: development
  data:
    neo4j:
      uri: 'bolt://localhost:7687'
      #auto-index: validate
      use-native-types: true
  datasource:
    url: 'jdbc:postgresql://localhost/postgres'
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    # generate-ddl: true
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: testorkg@gmail.com
    password: testorkg123
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
    protocol: smtp
    test-connection: false
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.neo4j.ogm.drivers.bolt.request.BoltRequest: DEBUG
my:
  cron:
    value: 0/3 * * * * *
