= Observatories

Observatories are groups of experts affiliated with different institutions that curates and organize ORKG content for a specific discipline.
Observatories represent groups which are managed by <<organizations>>.
One Observatory can be managed by many organizations.

[[observatories-fetch]]
== Fetching Observatories

A `GET` request provides information about an observatory.

operation::observatories-fetch[snippets='path-parameters,curl-request,http-response,response-fields']

[[observatories-list]]
== Listing Observatories

A `GET` request returns a <<sorting-and-pagination,paged>> list of <<observatories-fetch,observatories>>.
If no paging request parameters are provided, the default values will be used.

NOTE: Request parameters cannot be combined for this endpoint.

operation::observatories-index[snippets='query-parameters,curl-request']

[[observatories-create]]
== Creating Observatories

A `POST` request creates a new observatory with the given parameters.
The response will be `201 Created` when successful.
The observatory can be retrieved by following the URI in the `Location` header field.

NOTE: The response body contains the created observatory for convenience. This might be subject to change.

operation::observatories-create[snippets='request-fields,curl-request,response-headers,http-response']

[[observatories-edit]]
== Updating Observatories

A `PATCH` request updates an existing observatory with the given parameters.
Only fields provided in the request, and therefore non-null, will be updated.
The response will be `204 No Content` when successful.
The updated observatory (object) can be retrieved by following the URI in the `Location` header field.

NOTE: This endpoint can only be accessed by curators.

operation::observatories-update[snippets='path-parameters,request-fields,curl-request,response-headers,http-response']

[[observatories-list-papers]]
== Listing Papers of Observatories

A `GET` request returns a <<sorting-and-pagination,paged>> list of paper <<resources-fetch,resources>>.

TIP: This call features filter configs, check the chapter <<filter-config>> for more information on filter configs.

operation::observatory-resources-get-paged-with-filter-config[snippets='path-parameters,curl-request,query-parameters']

NOTE: Sorting is supported for the following fields: `id`, `created_by`, `created_at`.
It is also possible to sort by the matched value of each search filter.
To sort by the first search filter, the parameter `value0` can be used.
If a second search filter is defined, the parameter `value1` can be used.
By default, elements are sorted by `created_at` (descending).
