package org.orkg.contenttypes.domain.actions

import org.orkg.contenttypes.domain.actions.comparisons.CreateComparisonAction
import org.orkg.contenttypes.domain.actions.comparisons.PublishComparisonAction
import org.orkg.contenttypes.domain.actions.comparisons.UpdateComparisonAction
import org.orkg.contenttypes.domain.actions.contributions.ContributionAction
import org.orkg.contenttypes.domain.actions.literaturelists.CreateLiteratureListAction
import org.orkg.contenttypes.domain.actions.literaturelists.PublishLiteratureListAction
import org.orkg.contenttypes.domain.actions.literaturelists.UpdateLiteratureListAction
import org.orkg.contenttypes.domain.actions.literaturelists.sections.CreateLiteratureListSectionAction
import org.orkg.contenttypes.domain.actions.literaturelists.sections.DeleteLiteratureListSectionAction
import org.orkg.contenttypes.domain.actions.literaturelists.sections.UpdateLiteratureListSectionAction
import org.orkg.contenttypes.domain.actions.papers.CreatePaperAction
import org.orkg.contenttypes.domain.actions.papers.DeletePaperAction
import org.orkg.contenttypes.domain.actions.papers.PublishPaperAction
import org.orkg.contenttypes.domain.actions.papers.UpdatePaperAction
import org.orkg.contenttypes.domain.actions.rosettastone.statements.CreateRosettaStoneStatementAction
import org.orkg.contenttypes.domain.actions.rosettastone.statements.UpdateRosettaStoneStatementAction
import org.orkg.contenttypes.domain.actions.rosettastone.templates.CreateRosettaStoneTemplateAction
import org.orkg.contenttypes.domain.actions.rosettastone.templates.UpdateRosettaStoneTemplateAction
import org.orkg.contenttypes.domain.actions.smartreviews.CreateSmartReviewAction
import org.orkg.contenttypes.domain.actions.smartreviews.PublishSmartReviewAction
import org.orkg.contenttypes.domain.actions.smartreviews.UpdateSmartReviewAction
import org.orkg.contenttypes.domain.actions.smartreviews.sections.CreateSmartReviewSectionAction
import org.orkg.contenttypes.domain.actions.smartreviews.sections.DeleteSmartReviewSectionAction
import org.orkg.contenttypes.domain.actions.smartreviews.sections.UpdateSmartReviewSectionAction
import org.orkg.contenttypes.domain.actions.tables.CreateTableAction
import org.orkg.contenttypes.domain.actions.tables.UpdateTableAction
import org.orkg.contenttypes.domain.actions.tables.cells.UpdateTableCellAction
import org.orkg.contenttypes.domain.actions.tables.columns.CreateTableColumnAction
import org.orkg.contenttypes.domain.actions.tables.columns.DeleteTableColumnAction
import org.orkg.contenttypes.domain.actions.tables.columns.UpdateTableColumnAction
import org.orkg.contenttypes.domain.actions.tables.rows.CreateTableRowAction
import org.orkg.contenttypes.domain.actions.tables.rows.DeleteTableRowAction
import org.orkg.contenttypes.domain.actions.tables.rows.UpdateTableRowAction
import org.orkg.contenttypes.domain.actions.templates.CreateTemplateAction
import org.orkg.contenttypes.domain.actions.templates.UpdateTemplateAction
import org.orkg.contenttypes.domain.actions.templates.instances.UpdateTemplateInstanceAction
import org.orkg.contenttypes.domain.actions.templates.properties.CreateTemplatePropertyAction
import org.orkg.contenttypes.domain.actions.templates.properties.UpdateTemplatePropertyAction
import org.orkg.contenttypes.domain.actions.visualizations.VisualizationAction
import org.orkg.contenttypes.input.CreateComparisonRelatedFigureUseCase
import org.orkg.contenttypes.input.CreateComparisonRelatedResourceUseCase
import org.orkg.contenttypes.input.CreateComparisonUseCase
import org.orkg.contenttypes.input.CreateContributionUseCase
import org.orkg.contenttypes.input.CreateLiteratureListSectionUseCase
import org.orkg.contenttypes.input.CreateLiteratureListUseCase
import org.orkg.contenttypes.input.CreatePaperUseCase
import org.orkg.contenttypes.input.CreateRosettaStoneStatementUseCase
import org.orkg.contenttypes.input.CreateRosettaStoneTemplateUseCase
import org.orkg.contenttypes.input.CreateSmartReviewSectionUseCase
import org.orkg.contenttypes.input.CreateSmartReviewUseCase
import org.orkg.contenttypes.input.CreateTableColumnUseCase
import org.orkg.contenttypes.input.CreateTableRowUseCase
import org.orkg.contenttypes.input.CreateTableUseCase
import org.orkg.contenttypes.input.CreateTemplatePropertyUseCase
import org.orkg.contenttypes.input.CreateTemplateUseCase
import org.orkg.contenttypes.input.CreateVisualizationUseCase
import org.orkg.contenttypes.input.DeleteLiteratureListSectionUseCase
import org.orkg.contenttypes.input.DeletePaperUseCase
import org.orkg.contenttypes.input.DeleteSmartReviewSectionUseCase
import org.orkg.contenttypes.input.DeleteTableColumnUseCase
import org.orkg.contenttypes.input.DeleteTableRowUseCase
import org.orkg.contenttypes.input.PublishComparisonUseCase
import org.orkg.contenttypes.input.PublishLiteratureListUseCase
import org.orkg.contenttypes.input.PublishPaperUseCase
import org.orkg.contenttypes.input.PublishSmartReviewUseCase
import org.orkg.contenttypes.input.UpdateComparisonRelatedFigureUseCase
import org.orkg.contenttypes.input.UpdateComparisonRelatedResourceUseCase
import org.orkg.contenttypes.input.UpdateComparisonUseCase
import org.orkg.contenttypes.input.UpdateLiteratureListSectionUseCase
import org.orkg.contenttypes.input.UpdateLiteratureListUseCase
import org.orkg.contenttypes.input.UpdatePaperUseCase
import org.orkg.contenttypes.input.UpdateRosettaStoneStatementUseCase
import org.orkg.contenttypes.input.UpdateRosettaStoneTemplateUseCase
import org.orkg.contenttypes.input.UpdateSmartReviewSectionUseCase
import org.orkg.contenttypes.input.UpdateSmartReviewUseCase
import org.orkg.contenttypes.input.UpdateTableCellUseCase
import org.orkg.contenttypes.input.UpdateTableColumnUseCase
import org.orkg.contenttypes.input.UpdateTableRowUseCase
import org.orkg.contenttypes.input.UpdateTableUseCase
import org.orkg.contenttypes.input.UpdateTemplateInstanceUseCase
import org.orkg.contenttypes.input.UpdateTemplatePropertyUseCase
import org.orkg.contenttypes.input.UpdateTemplateUseCase

internal typealias BakedStatement = Triple<String, String, String>

internal typealias CreateComparisonCommand = CreateComparisonUseCase.CreateCommand
internal typealias CreateComparisonRelatedFigureCommand = CreateComparisonRelatedFigureUseCase.CreateCommand
internal typealias CreateComparisonRelatedResourceCommand = CreateComparisonRelatedResourceUseCase.CreateCommand
internal typealias CreateContributionCommand = CreateContributionUseCase.CreateCommand
internal typealias CreateLiteratureListCommand = CreateLiteratureListUseCase.CreateCommand
internal typealias CreateLiteratureListSectionCommand = CreateLiteratureListSectionUseCase.CreateCommand
internal typealias CreatePaperCommand = CreatePaperUseCase.CreateCommand
internal typealias CreateRosettaStoneStatementCommand = CreateRosettaStoneStatementUseCase.CreateCommand
internal typealias CreateRosettaStoneTemplateCommand = CreateRosettaStoneTemplateUseCase.CreateCommand
internal typealias CreateSmartReviewCommand = CreateSmartReviewUseCase.CreateCommand
internal typealias CreateSmartReviewSectionCommand = CreateSmartReviewSectionUseCase.CreateCommand
internal typealias CreateTableCommand = CreateTableUseCase.CreateCommand
internal typealias CreateTableColumnCommand = CreateTableColumnUseCase.CreateCommand
internal typealias CreateTableRowCommand = CreateTableRowUseCase.CreateCommand
internal typealias CreateTemplateCommand = CreateTemplateUseCase.CreateCommand
internal typealias CreateTemplatePropertyCommand = CreateTemplatePropertyUseCase.CreateCommand
internal typealias CreateVisualizationCommand = CreateVisualizationUseCase.CreateCommand

internal typealias UpdateComparisonCommand = UpdateComparisonUseCase.UpdateCommand
internal typealias UpdateComparisonRelatedFigureCommand = UpdateComparisonRelatedFigureUseCase.UpdateCommand
internal typealias UpdateComparisonRelatedResourceCommand = UpdateComparisonRelatedResourceUseCase.UpdateCommand
internal typealias UpdateLiteratureListCommand = UpdateLiteratureListUseCase.UpdateCommand
internal typealias UpdateLiteratureListSectionCommand = UpdateLiteratureListSectionUseCase.UpdateCommand
internal typealias UpdatePaperCommand = UpdatePaperUseCase.UpdateCommand
internal typealias UpdateRosettaStoneStatementCommand = UpdateRosettaStoneStatementUseCase.UpdateCommand
internal typealias UpdateRosettaStoneTemplateCommand = UpdateRosettaStoneTemplateUseCase.UpdateCommand
internal typealias UpdateSmartReviewCommand = UpdateSmartReviewUseCase.UpdateCommand
internal typealias UpdateSmartReviewSectionCommand = UpdateSmartReviewSectionUseCase.UpdateCommand
internal typealias UpdateTableCommand = UpdateTableUseCase.UpdateCommand
internal typealias UpdateTableCellCommand = UpdateTableCellUseCase.UpdateCommand
internal typealias UpdateTableColumnCommand = UpdateTableColumnUseCase.UpdateCommand
internal typealias UpdateTableRowCommand = UpdateTableRowUseCase.UpdateCommand
internal typealias UpdateTemplateCommand = UpdateTemplateUseCase.UpdateCommand
internal typealias UpdateTemplateInstanceCommand = UpdateTemplateInstanceUseCase.UpdateCommand
internal typealias UpdateTemplatePropertyCommand = UpdateTemplatePropertyUseCase.UpdateCommand

internal typealias DeletePaperCommand = DeletePaperUseCase.DeleteCommand
internal typealias DeleteLiteratureListSectionCommand = DeleteLiteratureListSectionUseCase.DeleteCommand
internal typealias DeleteSmartReviewSectionCommand = DeleteSmartReviewSectionUseCase.DeleteCommand
internal typealias DeleteTableColumnCommand = DeleteTableColumnUseCase.DeleteCommand
internal typealias DeleteTableRowCommand = DeleteTableRowUseCase.DeleteCommand

internal typealias PublishComparisonCommand = PublishComparisonUseCase.PublishCommand
internal typealias PublishLiteratureListCommand = PublishLiteratureListUseCase.PublishCommand
internal typealias PublishPaperCommand = PublishPaperUseCase.PublishCommand
internal typealias PublishSmartReviewCommand = PublishSmartReviewUseCase.PublishCommand

internal typealias CreateComparisonState = CreateComparisonAction.State
internal typealias CreateLiteratureListSectionState = CreateLiteratureListSectionAction.State
internal typealias CreateLiteratureListState = CreateLiteratureListAction.State
internal typealias CreatePaperState = CreatePaperAction.State
internal typealias CreateRosettaStoneStatementState = CreateRosettaStoneStatementAction.State
internal typealias CreateRosettaStoneTemplateState = CreateRosettaStoneTemplateAction.State
internal typealias CreateSmartReviewSectionState = CreateSmartReviewSectionAction.State
internal typealias CreateSmartReviewState = CreateSmartReviewAction.State
internal typealias CreateTableState = CreateTableAction.State
internal typealias CreateTableColumnState = CreateTableColumnAction.State
internal typealias CreateTableRowState = CreateTableRowAction.State
internal typealias CreateTemplatePropertyState = CreateTemplatePropertyAction.State
internal typealias CreateTemplateState = CreateTemplateAction.State

internal typealias UpdateComparisonState = UpdateComparisonAction.State
internal typealias UpdateLiteratureListSectionState = UpdateLiteratureListSectionAction.State
internal typealias UpdateLiteratureListState = UpdateLiteratureListAction.State
internal typealias UpdatePaperState = UpdatePaperAction.State
internal typealias UpdateRosettaStoneStatementState = UpdateRosettaStoneStatementAction.State
internal typealias UpdateRosettaStoneTemplateState = UpdateRosettaStoneTemplateAction.State
internal typealias UpdateSmartReviewSectionState = UpdateSmartReviewSectionAction.State
internal typealias UpdateSmartReviewState = UpdateSmartReviewAction.State
internal typealias UpdateTableState = UpdateTableAction.State
internal typealias UpdateTableCellState = UpdateTableCellAction.State
internal typealias UpdateTableColumnState = UpdateTableColumnAction.State
internal typealias UpdateTableRowState = UpdateTableRowAction.State
internal typealias UpdateTemplateInstanceState = UpdateTemplateInstanceAction.State
internal typealias UpdateTemplatePropertyState = UpdateTemplatePropertyAction.State
internal typealias UpdateTemplateState = UpdateTemplateAction.State

internal typealias PublishComparisonState = PublishComparisonAction.State
internal typealias PublishPaperState = PublishPaperAction.State

internal typealias PublishLiteratureListState = PublishLiteratureListAction.State
internal typealias PublishSmartReviewState = PublishSmartReviewAction.State

internal typealias DeletePaperState = DeletePaperAction.State
internal typealias DeleteLiteratureListSectionState = DeleteLiteratureListSectionAction.State
internal typealias DeleteSmartReviewSectionState = DeleteSmartReviewSectionAction.State
internal typealias DeleteTableColumnState = DeleteTableColumnAction.State
internal typealias DeleteTableRowState = DeleteTableRowAction.State

internal typealias ContributionState = ContributionAction.State
internal typealias VisualizationState = VisualizationAction.State
