= Statistics

Statistics are a way to obtain valuable information about the state of the graph.
Every data point is provided by a predefined metric, which are organized in groups.

[[statistics-list-groups]]
== Listing Groups

A `GET` request provides a list of all available metric groups.

operation::statistics_find-all-groups[snippets='curl-request,http-response,response-fields']

[[statistics-list-metrics-of-group]]
== Listing Metrics of Groups

A `GET` request provides a list of all available metrics of a given group.

operation::statistics_find-all-metrics-by-group[snippets='path-parameters,curl-request,http-response,response-fields']

[[statistics-fetch-metric]]
== Fetching Metrics

A `GET` request provides information about a given metric within a group.

[NOTE]
====
The values of some metrics are cached and therefore might not reflect the real value of the metric at that point in time.
====

operation::statistics_find-metric-by-group-and-name[snippets='path-parameters,curl-request,http-response,response-fields']
