= Contributions

Contributions represent a collection of concepts in the knowledge graph.
They can be seen as a collection of <<Resources,resources>>, <<Literals,literals>> and <<Predicates,predicates>>.
The provided endpoints aggregate these concepts and provide a unified contribution representation.

NOTE: The following endpoints use content negotiation, meaning that the contents of the response json depend on the specified `Accept` and `Content-Type` headers of each request.

[[contributions-fetch]]
== Fetching Contributions

A `GET` request provides information about a contribution.

operation::contributions-get-single[snippets='path-parameters,curl-request,http-response,response-fields']

[[contributions-list]]
== Listing Contributions

A `GET` request returns a <<sorting-and-pagination,paged>> list of <<contributions-fetch,contributions>>.
If no paging request parameters are provided, the default values will be used.

operation::contributions-get-paged[snippets='curl-request']

[[contributions-create]]
== Creating Contributions

A `POST` request creates a new contribution with all the given parameters.
The response will be `201 Created` when successful.
The contribution (object) can be retrieved by following the URI in the `Location` header field.

operation::contributions-create[snippets='request-fields,curl-request,http-response']
