= Table Columns

The following endpoints can be used to manipulate individual columns of tables.

NOTE: The following endpoints use content negotiation, meaning that the contents of the response json depend on the specified `Accept` and `Content-Type` headers of each request.

[[table-columns-create]]
== Creating Table Columns

A `POST` request creates a new table column with the given parameters.
The response will be `201 Created` when successful.
The updated table (object) can be retrieved by following the URI in the `Location` header field.

operation::tables-create-table-column-at-index[snippets='path-parameters,request-fields,curl-request,response-headers,http-response']

[[table-columns-edit]]
== Updating Table Columns

A `PUT` request updates an existing column of a table with the given parameters.
The response will be `204 No Content` when successful.
The updated table (object) can be retrieved by following the URI in the `Location` header field.

operation::tables-update-table-column[snippets='path-parameters,request-fields,curl-request,response-headers,http-response']

[[table-columns-delete]]
== Deleting Table Columns

A `DELETE` request deletes an existing column of a table.
The response will be `204 No Content` when successful.
The updated table (object) can be retrieved by following the URI in the `Location` header field.

operation::tables-delete-table-column[snippets='path-parameters,curl-request,http-response']
