= Template Instances

Template instances are an abstraction for a subgraph of <<Statements,statements>>, which is defined by a <<templates,template>>.

NOTE: The following endpoints use content negotiation, meaning that the contents of the response json depend on the specified `Accept` and `Content-Type` headers of each request.

[[template-instances-fetch]]
== Fetching Template Instances

A `GET` request provides information about a template instance.

operation::template-instances_get-single[snippets='path-parameters,curl-request,http-response,response-fields']

[[template-instances-list]]
== Listing Template Instances

A `GET` request returns a <<sorting-and-pagination,paged>> list of <<template-instances-fetch,template instances>>.
If no paging request parameters are provided, the default values will be used.

operation::template-instances_get-paged[snippets='curl-request']

The following list of request parameters are supported:

operation::template-instances_get-paged-with-parameters[snippets='query-parameters,curl-request']

[[template-instances-edit]]
== Updating Template Instances

A `PUT` request updates an existing template instance with all the given parameters.
The response will be `204 No Content` when successful.
The updated template instance (object) can be retrieved by following the URI in the `Location` header field.

operation::template-instances_update[snippets='path-parameters,request-fields,curl-request,response-headers,http-response']
