[versions]
forkhandles = "2.0.0.0"
junit5 = "5.8.2"
kotest = "5.4.0"
kotlinx-coroutines = "1.6.4"
testcontainers = "1.17.3"
spring-boot = "2.3.4.RELEASE"
spring-dependency-management = "1.0.11.RELEASE"

[libraries]
# BOMs
bytebuddy-bom = { module = "net.bytebuddy:byte-buddy-parent", version = "1.12.21" }
forkhandles-bom = { module = "dev.forkhandles:forkhandles-bom", version.ref = "forkhandles" }
junit5-bom = { module = "org.junit:junit-bom", version.ref = "junit5" }
kotlinx-coroutines-bom = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-bom", version.ref = "kotlinx-coroutines" }
spring-boot-bom = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
# Libraries
annotations-jsr305 = { module = "com.google.code.findbugs:jsr305", version = "3.0.2" }
forkhandles-result4k = { module = "dev.forkhandles:result4k", version.ref = "forkhandles" }
forkhandles-values4k = { module = "dev.forkhandles:values4k", version.ref = "forkhandles" }
javax-activation = { module = "javax.activation:activation", version = "1.1" }
jaxb-api = { module = "javax.xml.bind:jaxb-api", version = "2.3.0" }
jaxb-runtime = { module = "org.glassfish.jaxb:jaxb-runtime", version = "2.3.7" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }
kotest-runner = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
testcontainers-core = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
testcontainers-junit5 = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }
testcontainers-neo4j = { module = "org.testcontainers:neo4j", version.ref = "testcontainers" }
testcontainers-postgresql = { module = "org.testcontainers:postgresql", version.ref = "testcontainers" }

[bundles]
jaxb = ["javax-activation", "jaxb-api", "jaxb-runtime"]
kotest = ["kotest-runner", "kotest-assertions-core", "kotest-property"]
testcontainers = ["testcontainers-core", "testcontainers-junit5", "testcontainers-postgresql", "testcontainers-neo4j"]

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
