= Authentication (AuthN)

Authentication is done via the OAuth2 protocol.
An authentication token needs to be obtained and provided to protected endpoints.

NOTE: This endpoint only delivers information about the currenly logged in user.
      If you need to obtain information about other users in the system, check the <<contributors>> section.

== Obtaining an Access Token

A token can be obtained by sending a `POST` request to the `/oauth/token` endpoint.
The client needs to provide its client ID and secret via basic authentication (base64-encoded).
All request parameters need to be passed in `application/x-www-form-urlencoded`.
The parameters are:

`grant_type`:: Always `password`.
`username`:: The email address of the user.
`password`:: The password defined by the user.

The response will contain the access token and time of invalidation.
Obtaining a new token is only possible by re-authenticating to the API.

Example:

  curl -X POST --user 'orkg-client:secret' -d 'grant_type=password&username=user@example.org&password=password' http://localhost:8000/oauth/token

[NOTE]
====
Command line users can save the token directly to a variable and use this in following requests. e.g.

  export TOKEN=$(curl --silent -X POST --user 'orkg-client:secret' -d 'grant_type=password&username=user@example.org&password=password' http://localhost:8000/oauth/token | jq -r '.access_token')
====

== Using the Token

Tokens can be provided to the API via the `Authorization` header field with the `bearer` authentication type.
Authorization will be performed on tokens only.

Example:

    curl  -H "Accept: application/json" -H "Authorization: Bearer $TOKEN" -X GET http://localhost:8000/api/auth/user

== Fetching User Information

User information about the currently logged-in user can be obtained from the `/api/user/` endpoint via `GET` requests.
An authentication token needs to be provided.

Other contributor information can be obtained individually from `/api/user/\{id}`, where `\{id}` is a UUID of the user.
This will only provide selected properties for display purposes; currently the ID and the display name.

== Updating User Information

User information can be changed via a `PUT` request to the `/api/user/` endpoint.
An authentication token needs to be provided.

To change the user name, the `display_name` key needs to be present in the body.

== Updating Passwords

Passwords can be changed via a `PUT` request to the `/api/user/password` endpoint.
An authentication token needs to be provided.


To change the password, the `current_password`, `new_password` and `new_matching_password` keys need to be present in the body.
The `current_password` must match the current password of the user.
Additionally, `new_password` and `new_matching_password` need to contain the same values.


== Registering a User

New user accounts can be registered via a `POST` request to the `/api/auth/register` endpoint.

The `email`, `password` and `matching_password` keys need to be provided in the request body.
An optional `name` key can be provided to set the display name of the user (non-blank).

The endpoint will return the user data of the generated user.
