= Bulk Statements

Bulk operations on statements. Helps performing multiple calls together.

[[bulk-statements-fetch-by-subject]]
== Fetching Statements by Subjects (Bulk)

A `GET` request to get statements of multiple resources in the subject position.

operation::bulk-statements-lookup-by-subjects[snippets='query-parameters,curl-request,http-response,response-fields']

[[bulk-statements-fetch-by-object]]
== Fetching Statements by Objects (Bulk)

A `GET` request to get statements of multiple resources/literals in the object position.

operation::bulk-statements-lookup-by-objects[snippets='query-parameters,curl-request,http-response,response-fields']

[[bulk-statements-edit]]
== Updating Statements (Bulk)

A `PUT` request to edit multiple statements, with the same update body

operation::bulk-statements-edit-resource-statements[snippets='query-parameters,curl-request,http-response,response-fields']

[[bulk-statements-delete]]
== Deleting Statements (Bulk)

A `DELETE` request to delete multiple statements simultaneously

operation::bulk-statements-delete[snippets='query-parameters,curl-request,http-response']
