= Comparisons

Comparisons represent a collection of concepts in the knowledge graph.
They can be seen as a collection of <<Resources,resources>>, <<Literals,literals>> and <<Predicates,predicates>>.
The provided endpoints aggregate these concepts into a comparison representation.

NOTE: The following endpoints use content negotiation, meaning that the contents of the response json depend on the specified `Accept` and `Content-Type` headers of each request.

[[comparisons-fetch]]
== Fetching Comparisons

A `GET` request provides information about a comparison.

operation::comparisons-get-single[snippets='path-parameters,curl-request,http-response,response-fields']

[[comparisons-list]]
== Listing Comparisons

A `GET` request returns a <<sorting-and-pagination,paged>> list of <<comparisons-fetch,comparisons>>.
If no paging request parameters are provided, the default values will be used.

NOTE: Fetching comparisons by DOI, title or contributor does also return previous versions of comparisons.

operation::comparisons-get-paged[snippets='curl-request']

The following list of request parameters are supported:

operation::comparisons-get-paged-with-parameters[snippets='query-parameters,curl-request']

[[comparisons-create]]
== Creating Comparisons

A `POST` request creates a new comparison with all the given parameters.
The response will be `201 Created` when successful.
The comparison (object) can be retrieved by following the URI in the `Location` header field.

operation::comparisons-create[snippets='request-fields,curl-request,response-headers,http-response']

[[comparisons-edit]]
== Updating Comparisons

A `PUT` request updates an existing comparison with all the given parameters.
The response will be `204 No Content` when successful.
The updated comparison (object) can be retrieved by following the URI in the `Location` header field.

NOTE: All fields at the top level in the request can be omitted or `null`, meaning that the corresponding fields should not be updated.

WARNING: Author names will not be updated if a resource id is specified for a given author.

operation::comparisons-update[snippets='path-parameters,request-fields,curl-request,response-headers,http-response']

[[comparisons-publish]]
== Publishing Comparisons

A `POST` request publishes an existing comparison with the given parameters.
It automatically adds additional publication information, such as month and year published.
All comparison cell contents will be archived in a separate database.
Optionally, a DOI can be assigned to the comparison resource.
The response will be `201 Created` when successful.
The published comparison (object) can be retrieved by following the URI in the `Location` header field.

operation::comparisons-publish[snippets='path-parameters,request-fields,curl-request,response-headers,http-response']
