= Comparison Related Figures

Comparison Related Figures represent a collection of concepts in the knowledge graph and can be seen as a collection of <<Resources,resources>>, <<Literals,literals>> and <<Predicates,predicates>>.
They are used to define figures for comparisons.
The provided endpoints aggregate these concepts into a comparison related figure representation.

NOTE: The following endpoints use content negotiation, meaning that the contents of the response json depend on the specified `Accept` and `Content-Type` headers of each request.

[[comparisons-related-figure-fetch]]
== Fetching Comparison Related Figures

A `GET` request provides information about a comparison related figure.

operation::comparisons-related-figure-get-single[snippets='path-parameters,curl-request,http-response,response-fields']

[[comparisons-related-figure-list]]
== Listing Comparison Related Figures

A `GET` request returns a <<sorting-and-pagination,paged>> list of <<comparisons-related-figure-fetch,comparison related figures>>.

operation::comparisons-related-figure-get-paged[snippets='path-parameters,curl-request']

[[comparisons-related-figure-create]]
== Creating Comparison Related Figures

A `POST` request creates a new comparison related figure with all the given parameters.
The response will be `201 Created` when successful.
The comparison related figure (object) can be retrieved by following the URI in the `Location` header field.

operation::comparisons-create-comparison-related-figure-test[snippets='path-parameters,request-fields,curl-request,response-headers,http-response']

[[comparisons-related-figure-edit]]
== Updating Comparison Related Figures

A `PUT` request updates an existing comparison related figure with all the given parameters.
The response will be `204 No Content` when successful.
The updated comparison related figure (object) can be retrieved by following the URI in the `Location` header field.

NOTE: Top level fields that were mandatory when creating the comparison related figure can be omitted or `null`, meaning that the corresponding fields should not be updated.

operation::comparisons-update-comparison-related-figure[snippets='path-parameters,request-fields,curl-request,response-headers,http-response']

[[comparisons-related-figure-delete]]
== Deleting Comparison Related Figures

A `DELETE` request deletes a comparison related figure by ID.
The response will be `204 No Content` when successful.
The updated comparison (object) can be retrieved by following the URI in the `Location` header field.

operation::comparisons-related-figure-delete[snippets='path-parameters,curl-request,response-headers,http-response']
