= Datasets & Benchmarks

Some datasets and benchmarks on said datasets are imported into the ORKG.
Certain statistics can be obtained through the benchmark endpoint of the rest API.

[[research-fields-with-bechmark-list]]
== Listing Research Fields with Benchmarks

A `GET` request lists all the research fields with benchmarks (i.e., all research fields that have papers containing benchmarks in their contributions).

operation::benchmarks-fetch-research-fields-with-benchmarks[snippets='curl-request,http-response']


[[benchmarks-by-field-list]]
== Listing Benchmarks by Research Field

A `GET` request lists benchmarks under a certain research field.

operation::benchmarks-fetch-benchmark-summary-for-research-field[snippets='path-parameters,curl-request,http-response']


[[benchmarks-summary]]
== Listing Benchmark Summaries

A `GET` request lists the datasets for a research problem (a.k.a. Benchmark Summary)

operation::benchmarks-fetch-dataset-for-research-problem[snippets='path-parameters,curl-request,http-response']

[[benchmark-unpacked]]
== Listing Benchmarks (Unpacked)

A `GET` request lists summary for a dataset (a.k.a. Benchmark unpacked).

operation::benchmarks-fetch-dataset-summary[snippets='path-parameters,curl-request,http-response']
