= Literature List Sections

Literature Lists Sections represent a collection of concepts in the knowledge graph and can be seen as a collection of <<Resources,resources>>, <<Literals,literals>> and <<Predicates,predicates>>.
They are used to define the contents of a literature list.
The provided endpoints aggregate these concepts into a literature list section representation.

NOTE: The following endpoints use content negotiation, meaning that the contents of the response json depend on the specified `Accept` and `Content-Type` headers of each request.

[[literature-list-sections-text-sections]]
== Text Sections

[[literature-list-sections-create-text-section]]
=== Creating Text Sections

A `POST` request creates a new text section and adds it to the specified literature list.
The response will be `201 Created` when successful.
The updated literature list (object) can be retrieved by following the URI in the `Location` header field.

operation::literature-lists-create-text-section-at-index[snippets='path-parameters,request-fields,curl-request,http-response']

[[literature-list-sections-edit-text-section]]
=== Updating Text Sections

A `PUT` request updates an existing text section with all the given parameters.
The response will be `204 No Content` when successful.
The updated literature list (object) can be retrieved by following the URI in the `Location` header field.

operation::literature-lists-update-text-section[snippets='path-parameters,request-fields,curl-request,http-response']

[[literature-list-sections-list-sections]]
== List Sections

[[literature-list-sections-create-list-section]]
=== Creating List Sections

A `POST` request creates a new list section and adds it to the specified literature list.
The response will be `201 Created` when successful.
The updated literature list (object) can be retrieved by following the URI in the `Location` header field.

operation::literature-lists-create-list-section-at-index[snippets='path-parameters,request-fields,curl-request,http-response']

[[literature-list-sections-edit-list-section]]
=== Updating List Sections

A `PUT` request updates an existing list section with all the given parameters.
The response will be `204 No Content` when successful.
The updated literature list (object) can be retrieved by following the URI in the `Location` header field.

operation::literature-lists-update-list-section[snippets='path-parameters,request-fields,curl-request,http-response']

[[literature-list-sections-delete]]
== Deleting Literature List Sections

A `DELETE` request deletes a literature list section by ID.
The response will be `204 No Content` when successful.
The updated literature list (object) can be retrieved by following the URI in the `Location` header field.

operation::literature-lists-delete-section[snippets='path-parameters,curl-request,http-response']
