= Literature Lists

Literature Lists represent a collection of concepts in the knowledge graph.
They can be seen as a collection of <<Resources,resources>>, <<Literals,literals>> and <<Predicates,predicates>>.
The provided endpoints aggregate these concepts into a literature list representation.

NOTE: The following endpoints use content negotiation, meaning that the contents of the response json depend on the specified `Accept` and `Content-Type` headers of each request.

[[literature-lists-fetch]]
== Fetching Literature Lists

A `GET` request provides information about a literature list.

operation::literature-lists-get-single[snippets='curl-request,http-response,response-fields']

[[literature-lists-list]]
== Listing Literature Lists

A `GET` request returns a <<sorting-and-pagination,paged>> list of <<literature-lists-fetch,literature lists>>.
If no paging request parameters are provided, the default values will be used.

operation::literature-lists-get-paged[snippets='curl-request']

The following list of request parameters are supported:

operation::literature-lists-get-paged-with-parameters[snippets='query-parameters,curl-request']

[[literature-lists-create]]
== Creating Literature Lists

A `POST` request creates a new literature list with all the given parameters.
The response will be `201 Created` when successful.
The literature list (object) can be retrieved by following the URI in the `Location` header field.

operation::literature-lists-create[snippets='request-fields,curl-request,http-response']

[[literature-lists-edit]]
== Updating Literature Lists

A `PUT` request updates an existing literature list with all the given parameters.
The response will be `204 No Content` when successful.
The updated literature list (object) can be retrieved by following the URI in the `Location` header field.

NOTE: All fields at the top level in the request can be omitted or `null`, meaning that the corresponding fields should not be updated.

WARNING: Author names will not be updated if a resource id is specified for a given author.

operation::literature-lists-update[snippets='request-fields,curl-request,http-response']

[[literature-lists-publish]]
== Publishing Literature Lists

A `POST` request publishes an existing literature list with the given parameters.
In the process, a new literature list published resource is created and linked to the original literature list resource.
All statements containing the sections of the original literature list are archived in a separate database.
The response will be `201 Created` when successful.
The published literature list (object) can be retrieved by following the URI in the `Location` header field.

operation::literature-lists-publish[snippets='request-fields,curl-request,http-response']

[[literature-lists-published-contents]]
== Fetching Published Literature List Contents

A `GET` request returns contents of an already published literature list, at the state of publishing.

operation::literature-lists-find-published-content-by-id[snippets='curl-request']

Depending on the type of the requested content, the following representations are returned:

[options="header"]
|===
| Type     | Returned Representation
| Dataset  | <<resources-fetch,Resource>>
| Paper    | <<papers-fetch,Paper>>
| Software | <<resources-fetch,Resource>>
|===
