= Literals

Literals represent nodes in the knowledge graph.
They can appear in the object position in <<Statements,statements>>.

[[literals-fetch]]
== Fetching Literals

A `GET` request provides information about a literal.

operation::literals-get-single[snippets='path-parameters,curl-request,http-response,response-fields']

[[literals-list]]
== Listing Literals

A `GET` request returns a <<sorting-and-pagination,paged>> list of <<literals-fetch,literals>>.
If no paging request parameters are provided, the default values will be used.

operation::literals-get-paged[snippets='curl-request']

The following list of request parameters are supported:

operation::literals-get-paged-with-parameters[snippets='query-parameters,curl-request']

[[literals-create]]
== Creating Literals

A `POST` request creates a new literal with a given label (its value).
The response will be `201 Created` when successful.
The resource can be retrieved by following the URI in the `Location` header field.

NOTE: The created literal is returned in the body for convenience. This might be subject to change.

operation::literals-add[snippets='request-fields,curl-request,response-headers,http-response']

[[literals-edit]]
== Updating Literals

A `PUT` request updates a literal with a new value through the label property.
The response will be `200 OK` when successful.
The created literal is returned in the body for convenience.

operation::literals-edit[snippets='path-parameters,request-fields,curl-request,response-headers,http-response']
