= Organizations

Organizations represent institutes or groups.
These can handle further smaller groups named <<observatories>>.

[[organizations-fetch]]
== Fetching Organizations

A `GET` request provides information about a resource.

operation::organizations-fetch[snippets='curl-request,http-response,response-fields']

[[organizations-list]]
== Listing Organizations

A `GET` request lists all organizations:

operation::organizations-index[snippets='curl-request']

////
[[organization-create]]
== Creating organizations

A `POST` request creates a new organizations with a given name.
The response will be `200 Created` when successful.
The organization can be retrieved by following the URI in the `Location` header field.

// FIXME: implement missing test
operation::organization-controller-test-add[snippets='request-fields,curl-request,http-response']

The response body consists of the following fields:

// FIXME: implement missing test
operation::organization-controller-test-add[snippets='response-fields']
////
