= Organizations

Organizations represent institutes or groups.
These can handle further smaller groups named <<observatories>>.

[[organizations-fetch]]
== Fetching Organizations

A `GET` request provides information about a resource.

operation::organizations-fetch[snippets='path-parameters,curl-request,http-response,response-fields']

[[organizations-list]]
== Listing Organizations

A `GET` request lists all organizations:

operation::organizations-index[snippets='curl-request']

////
[[organization-create]]
== Creating organizations

A `POST` request creates a new organizations with a given name.
The response will be `200 Created` when successful.
The organization can be retrieved by following the URI in the `Location` header field.

// FIXME: implement missing test
operation::organization-controller-test-add[snippets='request-fields,curl-request,http-response']

The response body consists of the following fields:

// FIXME: implement missing test
operation::organization-controller-test-add[snippets='response-fields']
////

[[organizations-edit]]
== Updating Organizations
:operation-request-part-properties-fields-title: Request fields for properties part

A `PATCH` request updates an existing organization with the given parameters.
Only fields provided in the request, and therefore non-null, will be updated.
The response will be `204 No Content` when successful.
The updated organization (object) can be retrieved by following the URI in the `Location` header field.

NOTE: This endpoint can only be accessed by curators.

operation::organizations-update[snippets='path-parameters,request-parts,request-part-properties-fields,curl-request,http-response']
