= Papers

Papers represent a collection of concepts in the knowledge graph.
They can be seen as a collection of <<Resources,resources>>, <<Literals,literals>> and <<Predicates,predicates>>.
The provided endpoints aggregate these concepts into a paper representation.

NOTE: The following endpoints use content negotiation, meaning that the contents of the response json depend on the specified `Accept` and `Content-Type` headers of each request.

[[papers-fetch]]
== Fetching Papers

A `GET` request provides information about a paper.

operation::papers-get-single[snippets='path-parameters,curl-request,http-response,response-fields']

[[papers-contributors]]
== Fetching Contributors of Papers

A `GET` request returns a <<sorting-and-pagination,paged>> list of <<contributors,contributor>> ids.

operation::papers-get-contributors[snippets='path-parameters,curl-request']

[[papers-list]]
== Listing Papers

A `GET` request returns a <<sorting-and-pagination,paged>> list of <<papers-fetch,papers>>.
If no paging request parameters are provided, the default values will be used.

operation::papers-get-paged[snippets='curl-request']

The following list of request parameters are supported:

operation::papers-get-paged-with-parameters[snippets='query-parameters,curl-request']

[[papers-create]]
== Creating Papers

A `POST` request creates a new paper with all the given parameters.
The response will be `201 Created` when successful.
The paper (object) can be retrieved by following the URI in the `Location` header field.

operation::papers-create[snippets='request-fields,curl-request,http-response']

[[papers-edit]]
== Updating Papers

A `PUT` request updates an existing paper with all the given parameters.
The response will be `204 No Content` when successful.
The updated paper (object) can be retrieved by following the URI in the `Location` header field.

NOTE: All fields at the top level in the request can be omitted or `null`, meaning that the corresponding fields should not be updated.

WARNING: Author names will not be updated if a resource id is specified for a given author.

operation::papers-update[snippets='path-parameters,request-fields,curl-request,http-response']

[[papers-publish]]
== Publishing Papers

A `POST` request publishes an existing paper with the given parameters.
In the process, a new paper version resource is created and linked to the original paper resource.
All contribution statements of the original paper are archived in a separate database.
The response will be `201 Created` when successful.
The paper resource can be retrieved by following the URI in the `Location` header field.

operation::papers-publish[snippets='path-parameters,request-fields,curl-request,http-response']

[[papers-exist]]
== Checking for Existing Papers

A `HEAD` request provides information whether a paper exists in the knowledge graph or not.
The response will be `200 OK` when successful.
When the paper does not exist in the knowledge graph, the response will be `404 NOT FOUND`.
The found paper can be retrieved by following the URI in the `Location` header field.

=== Checking for Existing Papers by DOI

operation::papers-exists-by-doi[snippets='curl-request,query-parameters,http-response']

=== Checking for Existing Papers by Title

operation::papers-exists-by-title[snippets='curl-request,query-parameters,http-response']
