= Rosetta Stone Statements

Rosetta stone statements are instances of <<rosetta-stone-templates,rosetta stone templates>> and represent a semantically meaningful statement to a human reader.

NOTE: The following endpoints use content negotiation, meaning that the contents of the response json depend on the specified `Accept` and `Content-Type` headers of each request.

[[rosetta-stone-statements-fetch]]
== Fetching Rosetta Stone Statements

A `GET` request provides information about a rosetta stone statement or a specific rosetta stone statement version.

operation::rosetta-stone-statements-get-single[snippets='curl-request,http-response,response-fields']

[[rosetta-stone-statements-list]]
== Listing Rosetta Stone Statements

A `GET` request returns a <<sorting-and-pagination,paged>> list of <<rosetta-stone-statements-fetch,rosetta stone statements>>.
If no paging request parameters are provided, the default values will be used.

NOTE: Only the most recent versions of rosetta stone statements will be returned.

operation::rosetta-stone-statements-get-paged[snippets='curl-request']

The following list of request parameters are supported:

operation::rosetta-stone-statements-get-paged-with-parameters[snippets='query-parameters,curl-request']

[[rosetta-stone-statements-list-versions]]
== Listing Rosetta Stone Statement Versions

A `GET` request returns a list of <<rosetta-stone-statements-fetch,rosetta stone statement>> versions.

operation::rosetta-stone-statements-get-all-versions[snippets='curl-request']

[[rosetta-stone-statements-create]]
== Creating Rosetta Stone Statements

A `POST` request creates a new rosetta stone statement with all the given parameters.
The response will be `201 Created` when successful.
The rosetta stone statement can be retrieved by following the URI in the `Location` header field.

operation::rosetta-stone-statements-create[snippets='request-fields,curl-request,http-response']

[[rosetta-stone-statements-edit]]
== Updating Rosetta Stone Statements

A `POST` request creates a new version of an existing rosetta stone statement with all the given parameters.
The response will be `201 Created` when successful.
The revised rosetta stone statement (object) can be retrieved by following the URI in the `Location` header field.

operation::rosetta-stone-statements-update[snippets='request-fields,curl-request,http-response']

[[rosetta-stone-statements-delete]]
== Deleting Rosetta Stone Statements

=== Soft-Deleting Rosetta Stone Statements

A `DELETE` request soft-deletes a rosetta stone statement with all its versions.
The response will be `204 No Content` when successful.

operation::rosetta-stone-statements-soft-delete[snippets='path-parameters,curl-request,http-response']

=== Fully Deleting Rosetta Stone Statements

A `DELETE` request fully deletes a rosetta stone statement with all its versions.
The response will be `204 No Content` when successful.

NOTE: The user performing the action needs to be a curator.

operation::rosetta-stone-statements-delete[snippets='path-parameters,curl-request,http-response']
