= Rosetta Stone Templates

Rosetta Stone Templates represent a collection of concepts in the knowledge graph and can be seen as a collection of <<Resources,resources>>, <<Literals,literals>> and <<Predicates,predicates>>.
They can be used to model the structure of statements following the rosetta stone approach.
The provided endpoints aggregate these concepts into a rosetta stone template representation.

NOTE: The following endpoints use content negotiation, meaning that the contents of the response json depend on the specified `Accept` and `Content-Type` headers of each request.

[[rosetta-stone-templates-fetch]]
== Fetching Rosetta Stone Templates

A `GET` request provides information about a template.

operation::rosetta-stone-templates-get-single[snippets='curl-request,http-response,response-fields']

[[rosetta-stone-templates-list]]
== Listing Rosetta Stone Templates

A `GET` request returns a <<sorting-and-pagination,paged>> list of <<rosetta-stone-templates-fetch,rosetta stone templates>>.
If no paging request parameters are provided, the default values will be used.

operation::rosetta-stone-templates-get-paged[snippets='curl-request']

The following list of request parameters are supported:

operation::rosetta-stone-templates-get-paged-with-parameters[snippets='query-parameters']

[[rosetta-stone-templates-create]]
== Creating Rosetta Stone Templates

A `POST` request creates a new rosetta stone template with all the given parameters.
The response will be `201 Created` when successful.
The rosetta stone template (object) can be retrieved by following the URI in the `Location` header field.

NOTE: The first property of a rosetta stone template defines the subject position of the statement and is required to have a path of `hasSubjectPosition`, must have a minimum cardinality of at least one and is not a literal template property.
      All other properties define a object position, which must have a path of `hasObjectPosition`.
      At least one property is required to create a new rosetta stone template.

operation::rosetta-stone-templates-create[snippets='request-fields,curl-request,http-response']

[[rosetta-stone-templates-edit]]
== Updating Rosetta Stone Templates

A `PUT` request updates an existing rosetta stone template with all the given parameters.
The response will be `204 No Content` when successful.
The updated rosetta stone template (object) can be retrieved by following the URI in the `Location` header field.

NOTE: Only rosetta stone templates that have not been used to create a rosetta stone statement can be fully updated.
      Otherwise, it is only possible to add new object positions and to insert a section for that specific object position properties into the formatted label.

operation::rosetta-stone-templates-update[snippets='request-fields,curl-request,http-response']

[[rosetta-stone-templates-delete]]
== Deleting Rosetta Stone Templates

A `DELETE` request deletes a rosetta stone template.
The response will be `204 No Content` when successful.

NOTE: A rosetta stone template can only be deleted when it is not used for any <<rosetta-stone-statements,rosetta stone statement>>.

operation::rosetta-stone-templates-delete[snippets='path-parameters,curl-request,http-response']
