= Smart Reviews

Smart Reviews represent a collection of concepts in the knowledge graph.
They can be seen as a collection of <<Resources,resources>>, <<Literals,literals>> and <<Predicates,predicates>>.
The provided endpoints aggregate these concepts into a smart review representation.

NOTE: The following endpoints use content negotiation, meaning that the contents of the response json depend on the specified `Accept` and `Content-Type` headers of each request.

[[smart-reviews-fetch]]
== Fetching a smart review

A `GET` request provides information about a smart review.

operation::smart-reviews-get-single[snippets='curl-request,http-response,response-fields']

[[smart-reviews-list]]
== Listing smart reviews

A `GET` request returns a <<sorting-and-pagination,paged>> list of <<smart-reviews-fetch,smart reviews>>.
If no paging request parameters are provided, the default values will be used.

operation::smart-reviews-get-paged[snippets='curl-request']

The following list of request parameters are supported:

operation::smart-reviews-get-paged-with-parameters[snippets='request-parameters,curl-request']

[[smart-reviews-create]]
== Creating smart reviews

A `POST` request creates a new smart review with all the given parameters.
The response will be `201 Created` when successful.
The smart review (object) can be retrieved by following the URI in the `Location` header field.

operation::smart-reviews-create[snippets='request-fields,curl-request,http-response']

[[smart-reviews-edit]]
== Editing a smart review

A `PUT` request updates an existing smart review with all the given parameters.
The response will be `204 No Content` when successful.
The updated smart review (object) can be retrieved by following the URI in the `Location` header field.

NOTE: All fields at the top level in the request can be omitted or `null`, meaning that the corresponding fields should not be updated.

WARNING: Author names will not be updated if a resource id is specified for a given author.

operation::smart-reviews-update[snippets='request-fields,curl-request,http-response']

[[smart-reviews-publish]]
== Publishing smart reviews

A `POST` request publishes an existing smart review with the given parameters.
In the process, a new smart review published resource is created and linked to the original smart review resource.
All statements containing the sections of the original smart review are archived in a separate database.
Optionally, a DOI can be assigned to the published smart review resource.
The response will be `204 No Content` when successful.

operation::smart-reviews-publish[snippets='request-fields,curl-request,http-response']
