= Smart Review Sections

Smart Reviews Sections represent a collection of concepts in the knowledge graph and can be seen as a collection of <<Resources,resources>>, <<Literals,literals>> and <<Predicates,predicates>>.
They are used to define the contents of a smart review.
The provided endpoints aggregate these concepts into a smart review section representation.

NOTE: The following endpoints use content negotiation, meaning that the contents of the response json depend on the specified `Accept` and `Content-Type` headers of each request.

[[smart-review-sections-comparison-sections]]
== Comparison Sections

[[smart-review-sections-create-comparison-section]]
=== Creating Comparison Sections

A `POST` request creates a new comparison section and adds it to the specified smart review.
The response will be `201 Created` when successful.
The updated smart review (object) can be retrieved by following the URI in the `Location` header field.

operation::smart-reviews-create-comparison-section-at-index[snippets='path-parameters,request-fields,curl-request,response-headers,http-response']

[[smart-review-sections-edit-comparison-section]]
=== Updating Comparison Sections

A `PUT` request updates an existing comparison section with all the given parameters.
The response will be `204 No Content` when successful.
The updated smart review (object) can be retrieved by following the URI in the `Location` header field.

operation::smart-reviews-update-comparison-section[snippets='path-parameters,request-fields,curl-request,response-headers,http-response']

[[smart-review-sections-visualization-sections]]
== Visualization Sections

[[smart-review-sections-create-visualization-section]]
=== Creating Visualization Sections

A `POST` request creates a new visualization section and adds it to the specified smart review.
The response will be `201 Created` when successful.
The updated smart review (object) can be retrieved by following the URI in the `Location` header field.

operation::smart-reviews-create-visualization-section-at-index[snippets='path-parameters,request-fields,curl-request,response-headers,http-response']

[[smart-review-sections-edit-visualization-section]]
=== Updating Visualization Sections

A `PUT` request updates an existing visualization section with all the given parameters.
The response will be `204 No Content` when successful.
The updated smart review (object) can be retrieved by following the URI in the `Location` header field.

operation::smart-reviews-update-visualization-section[snippets='path-parameters,request-fields,curl-request,response-headers,http-response']

[[smart-review-sections-resource-sections]]
== Resource Sections

[[smart-review-sections-create-resource-section]]
=== Creating Resource Sections

A `POST` request creates a new resource section and adds it to the specified smart review.
The response will be `201 Created` when successful.
The updated smart review (object) can be retrieved by following the URI in the `Location` header field.

operation::smart-reviews-create-resource-section-at-index[snippets='path-parameters,request-fields,curl-request,response-headers,http-response']

[[smart-review-sections-edit-resource-section]]
=== Updating Resource Sections

A `PUT` request updates an existing resource section with all the given parameters.
The response will be `204 No Content` when successful.
The updated smart review (object) can be retrieved by following the URI in the `Location` header field.

operation::smart-reviews-update-resource-section[snippets='path-parameters,request-fields,curl-request,response-headers,http-response']

[[smart-review-sections-predicate-sections]]
== Predicate Sections

[[smart-review-sections-create-predicate-section]]
=== Creating Predicate Sections

A `POST` request creates a new predicate section and adds it to the specified smart review.
The response will be `201 Created` when successful.
The updated smart review (object) can be retrieved by following the URI in the `Location` header field.

operation::smart-reviews-create-predicate-section-at-index[snippets='path-parameters,request-fields,curl-request,response-headers,http-response']

[[smart-review-sections-edit-predicate-section]]
=== Updating Predicate Sections

A `PUT` request updates an existing predicate section with all the given parameters.
The response will be `204 No Content` when successful.
The updated smart review (object) can be retrieved by following the URI in the `Location` header field.

operation::smart-reviews-update-predicate-section[snippets='path-parameters,request-fields,curl-request,response-headers,http-response']

[[smart-review-sections-ontology-sections]]
== Ontology Sections

[[smart-review-sections-create-ontology-section]]
=== Creating Ontology Sections

A `POST` request creates a new ontology section and adds it to the specified smart review.
The response will be `201 Created` when successful.
The updated smart review (object) can be retrieved by following the URI in the `Location` header field.

operation::smart-reviews-create-ontology-section-at-index[snippets='path-parameters,request-fields,curl-request,response-headers,http-response']

[[smart-review-sections-edit-ontology-section]]
=== Updating Ontology Sections

A `PUT` request updates an existing ontology section with all the given parameters.
The response will be `204 No Content` when successful.
The updated smart review (object) can be retrieved by following the URI in the `Location` header field.

operation::smart-reviews-update-ontology-section[snippets='path-parameters,request-fields,curl-request,response-headers,http-response']

[[smart-review-sections-text-sections]]
== Text Sections

[[smart-review-sections-create-text-section]]
=== Creating Text Sections

A `POST` request creates a new text section and adds it to the specified smart review.
The response will be `201 Created` when successful.
The updated smart review (object) can be retrieved by following the URI in the `Location` header field.

operation::smart-reviews-create-text-section-at-index[snippets='path-parameters,request-fields,curl-request,response-headers,http-response']

[[smart-review-sections-edit-text-section]]
=== Updating Text Sections

A `PUT` request updates an existing text section with all the given parameters.
The response will be `204 No Content` when successful.
The updated smart review (object) can be retrieved by following the URI in the `Location` header field.

operation::smart-reviews-update-text-section[snippets='path-parameters,request-fields,curl-request,response-headers,http-response']

[[smart-review-sections-delete]]
== Deleting Smart Review Section

A `DELETE` request deletes a smart review section by ID.
The response will be `204 No Content` when successful.
The updated smart review (object) can be retrieved by following the URI in the `Location` header field.

operation::smart-reviews-delete-section[snippets='path-parameters,curl-request,response-headers,http-response']
