= Visualizations

Visualizations represent a collection of concepts in the knowledge graph.
They can be seen as a collection of <<Resources,resources>>, <<Literals,literals>> and <<Predicates,predicates>>.
The provided endpoints aggregate these concepts into a visualization representation.

NOTE: The following endpoints use content negotiation, meaning that the contents of the response json depend on the specified `Accept` and `Content-Type` headers of each request.

[[visualizations-fetch]]
== Fetching Visualizations

A `GET` request provides information about a visualization.

operation::visualizations-get-single[snippets='path-parameters,curl-request,http-response,response-fields']

[[visualizations-list]]
== Listing Visualizations

A `GET` request returns a <<sorting-and-pagination,paged>> list of <<visualizations-fetch,visualizations>>.
If no paging request parameters are provided, the default values will be used.

operation::visualizations-get-paged[snippets='curl-request']

The following list of request parameters are supported:

operation::visualizations-get-paged-with-parameters[snippets='query-parameters']

[[visualizations-create]]
== Creating Visualizations

A `POST` request creates a new visualization with all the given parameters.
The response will be `201 Created` when successful.
The visualization (object) can be retrieved by following the URI in the `Location` header field.

operation::visualizations-create[snippets='request-fields,curl-request,http-response']
