spring:
  data.web.pageable.max-page-size: 2500
  rdf:
    # Vocab prefix not used, still hard coded
    # might need to be copied to other profiles on deployment
    vocab-prefix: 'http://orkg.org/orkg'
    frontend-uri: 'http://localhost:3000'
  jmx:
    enabled: true
coffee-boots:
  cache:
    basic-spec: maximumSize=5000,expireAfterAccess=10m,recordStats
orkg:
  export:
    rdf:
      # cron schedule for the rdf-dump
      # use "-" to disable
      schedule: "-"
      file-name: rdf-export-orkg.nt
    unpublished-comparisons:
      # cron schedule for the unpublished comparisons export
      # use "-" to disable
      schedule: "-"
      file-name: comparisons.jsonl
  ranking:
    papers:
      # cron schedule for paper-ranking
      # use "-" to disable
      schedule: "-"
      workers: 10
      chunk-size: 1000
      log-file: 'paper-ranking.log'
  init:
    setup:
      entities-file: "data/required_entities.json"
  datacite:
    username: ""
    password: ""
    doiPrefix: "10.7484"
    url: "https://api.test.datacite.org/dois"
    publish: "draft"
  publishing:
    base-url:
      paper: "http://localhost/paper/"
      comparison: "http://localhost/comparison/"
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,info,jolokia,liquibase,loggers,env,metrics
    jmx:
      exposure:
        include: '*'
  endpoint:
    env:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true
    jolokia:
      enabled: true
    liquibase:
      enabled: true
    loggers:
      enabled: true
    metrics:
      enabled: true
hawtio:
  authenticationEnabled: false
---
spring:
  config:
    activate:
      on-profile:
        - development
  neo4j:
    uri: 'bolt://localhost:7687'
  datasource:
    url: 'jdbc:postgresql://localhost/postgres'
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    # generate-ddl: true
logging:
  level:
    org.springframework.data.neo4j: DEBUG
