spring:
  # Get rid of "org.postgresql.jdbc.PgConnection.createClob() not implemented" error, see
  # https://hibernate.atlassian.net/browse/HHH-12368
  jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true
  data.web.pageable.max-page-size: 2500
  rdf:
    # Vocab prefix not used, still hard coded
    # might need to be copied to other profiles on deployment
    vocab-prefix: 'http://orkg.org/orkg'
    frontend-uri: 'http://localhost:3000'
  jmx:
    enabled: true
coffee-boots:
  cache:
    basic-spec: maximumSize=5000,expireAfterAccess=10m,recordStats
orkg:
  init:
    setup:
      entities-file: "data/required_entities.json"
  datacite:
    username: ""
    password: ""
    doiPrefix: "10.7484"
    url: "https://api.test.datacite.org/dois"
    publish: "draft"
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,info,jolokia,liquibase,loggers,env,metrics
    jmx:
      exposure:
        include: '*'
  endpoint:
    env:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true
    jolokia:
      enabled: true
    liquibase:
      enabled: true
    loggers:
      enabled: true
    metrics:
      enabled: true
hawtio:
  authenticationEnabled: false
---
spring:
  profiles: development
  data:
    neo4j:
      uri: 'bolt://localhost:7687'
      #auto-index: validate
      use-native-types: true
  datasource:
    url: 'jdbc:postgresql://localhost/postgres'
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    # generate-ddl: true
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.neo4j.ogm.drivers.bolt.request.BoltRequest: DEBUG
