[[papers]]
== Papers

Papers represent a collection of concepts in the knowledge graph.
They can be seen as a collection of <<Resources,resources>>, <<Literals,literals>> and <<Predicates,predicates>>

[[papers-create]]
=== Creating papers

A `POST` request creates a new paper with all the given parameters.
The response will be `201 Created` when successful.
The paper root resource (object) can be retrieved by following the URI in the `Location` header field.

NOTE: The created paper root resource is returned in the body for convenience. This might be subject to change.

operation::paper-controller-test-add[snippets='request-fields,curl-request,http-response']

For more details on how the request would look like see https://gitlab.com/TIBHannover/orkg/orkg-backend/issues/77[Gitlab issue].

The response body consists of the following fields:

operation::paper-controller-test-add[snippets='response-fields']

NOTE: The Resources, Literals, Predicates part of the request are checked and an error is returned when some is missing or non-existing.
