= Testing

== Current status

In the prototyping stage, ORKG did not see much testing effort.
We work to improve the situation continuously by providing tests for newly written code and areas of the code that are modified and currently lack test.
Developers are expected to provide tests with every merge request.

== Test organization

There are currently two types of tests: __unit tests__, found in the `test` source sets, as well as __integration tests__, found in the `integrationTest` source set of the `rest-api-server` module.

_Unit tests_ should make out the largest portions of test, as described in the https://martinfowler.com/articles/practical-test-pyramid.html#TheTestPyramid[test pyramid].
They should be written in accordance to the FIRST principle (see https://agileinaflash.blogspot.com/2009/02/first.html[here]).
Because test code is code and therefore needs maintenance, only just enough test should be written.
A good guideline it the one proposed by Sandi Metz, as summarized in https://gist.github.com/Integralist/7944948[this write-up] and https://www.youtube.com/watch?v=URSWYvyc42M[her talk at Rails Conf 2013].
All code should be written with testability in mind since testability is a good indicator for code quality: clean code is usually easy to test.
Unit tests are additionally used to generate the API documentation using https://spring.io/projects/spring-restdocs[Spring REST Docs], as well as generating an OpenAPI specification using https://gitlab.com/TIBHannover/orkg/restdocs-api-spec[Spring REST Docs API Specification Integration].

Some of the tests in the `adapter-output` modules could be considered integration tests, as they instantiate some parts of the Spring Boot framework and connect to a database container.
But since they are mostly testing query construction, which does not work without a database, they could be considered unit tests.

The _integration tests_ are designed to test the full system as closely as possible to the production system.
They therefore use Docker containers during the test runs, using https://www.testcontainers.org/[TestContainers].
This results in an increased start-up and run time which slow the testing cycle down and should only be used for testing all components, start to finish.

== Testing with Spring Boot

Testing in Spring and Spring Boot is a complex topic due to the complexities of the framework.
To get started, the following articles from the "Reflectoring" blog are a recommended read:

* https://reflectoring.io/unit-testing-spring-boot/[Unit Testing with Spring Boot]
* https://reflectoring.io/spring-boot-test/[Integration Tests with @SpringBootTest]
* https://reflectoring.io/spring-boot-web-controller-test/[Testing Spring MVC Web Controllers with @WebMvcTest]
* https://reflectoring.io/spring-boot-data-jpa-test/[Testing JPA Queries with @DataJpaTest]

Another useful source is the https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-testing[chapter on testing] in the official Spring Boot documentation.

== Test Fixtures

Test fixtures are a consistent, predefined environment or set of data or functions to help in testing.
They are used to set up or teardown individual test cases, or used to populate databases, for configuration, or initializing objects.

=== Naming conventions

In oder to keep the code structured and helper functions findable for easier reuse, it is helpful to define basic guidelines on where certain pieces of code should be placed.
The following list defines a set of rules for organizing classes and functions for test fixtures:

- All factory methods should go to their own package, following naming structure of `org.orkg.\{module\}.testing.fixtures`, where `module` is the current context, e.g. "graph", "community", etc.
- All factory methods should go to a file, organized around the concept of the modules.
For example, `createResource()` could either go to `FactoryFunctions` or `ResourceFactoryFunctions`, depending on how many variants there are.
- Functions starting with `create` should have a deterministic behavior, meaning they create the same default instance every time.
- Functions providing random values should start with `random` and vary all of their attributes.
- Extension classes should have a name prefix, indicating the context of the extensions.
For example, a class with extension functions for `Fabrikate` should be named `FabrikateExtensions`.
