= Comparisons

Comparisons represent a collection of concepts in the knowledge graph.
They can be seen as a collection of <<Resources,resources>>, <<Literals,literals>> and <<Predicates,predicates>>.
The provided endpoints aggregate these concepts into a comparison representation.

NOTE: The following endpoints use content negotiation, meaning that the contents of the response json depend on the specified `Accept` and `Content-Type` headers of each request.

[[comparisons-fetch]]
== Fetching a comparison

A `GET` request provides information about a comparison.

operation::comparisons-get-single[snippets='curl-request,response-fields']

[[comparisons-list]]
== Listing comparisons

A `GET` request returns a <<sorting-and-pagination,paged>> list of <<comparisons-fetch,comparisons>>.
If no paging request parameters are provided, the default values will be used.

NOTE: Fetching comparisons by DOI, title or contributor does also return previous versions of comparisons.

operation::comparisons-get-paged[snippets='curl-request']

The following list of request parameters are supported:

NOTE: Only one request parameter can be used at a time.

operation::comparisons-get-paged[snippets='request-parameters']

[[comparisons-related-resource-fetch]]
== Fetching a related resource for a comparison

A `GET` request provides information about a comparison related resource.

operation::comparisons-related-resource-get-single[snippets='curl-request,response-fields']

[[comparisons-related-resource-list]]
== Listing related resources for a comparison

A `GET` request returns a <<sorting-and-pagination,paged>> list of <<comparisons-related-resource-fetch,comparison related resources>>.

operation::comparisons-related-resource-get-single[snippets='curl-request']

[[comparisons-related-figure-fetch]]
== Fetching a related figure for a comparison

A `GET` request provides information about a comparison related figure.

operation::comparisons-related-figure-get-single[snippets='curl-request,response-fields']

[[comparisons-related-figure-list]]
== Listing related figures for a comparison

A `GET` request returns a <<sorting-and-pagination,paged>> list of <<comparisons-related-figure-fetch,comparison related figures>>.

operation::comparisons-related-figure-get-single[snippets='curl-request']

[[comparisons-publish]]
== Publishing comparisons

A `POST` request publishes an existing comparison with the given parameters.
It assigns a DOI to the comparison and adds additional publication information, such as month and year published.
The response will be `204 No Content` when successful.

operation::comparisons-publish[snippets='request-fields,curl-request,http-response']
