= Literature List Sections

Literature Lists Sections represent a collection of concepts in the knowledge graph and can be seen as a collection of <<Resources,resources>>, <<Literals,literals>> and <<Predicates,predicates>>.
They are used to define the contents of a literature list.
The provided endpoints aggregate these concepts into a literature list section representation.

NOTE: The following endpoints use content negotiation, meaning that the contents of the response json depend on the specified `Accept` and `Content-Type` headers of each request.

[[literature-list-sections-text-sections]]
== Text Sections

[[literature-list-sections-create-text-section]]
=== Creating a text section

A `POST` request creates a new text section and appends it to the end of the literature list.
The response will be `201 Created` when successful.
The updated literature list (object) can be retrieved by following the URI in the `Location` header field.

operation::literature-lists-create-text-section[snippets='request-fields,curl-request,http-response']

[[literature-list-sections-edit-text-section]]
=== Editing a text section

A `PUT` request updates an existing text section with all the given parameters.
The response will be `204 No Content` when successful.
The updated literature list (object) can be retrieved by following the URI in the `Location` header field.

operation::literature-lists-update-text-section[snippets='request-fields,curl-request,http-response']

[[literature-list-sections-list-sections]]
== List Sections

[[literature-list-sections-create-list-section]]
=== Creating a list section

A `POST` request creates a new list section and appends it to the end of the literature list.
The response will be `201 Created` when successful.
The updated literature list (object) can be retrieved by following the URI in the `Location` header field.

operation::literature-lists-create-list-section[snippets='request-fields,curl-request,http-response']

[[literature-list-sections-edit-list-section]]
=== Editing a list section

A `PUT` request updates an existing list section with all the given parameters.
The response will be `204 No Content` when successful.
The updated literature list (object) can be retrieved by following the URI in the `Location` header field.

operation::literature-lists-update-list-section[snippets='request-fields,curl-request,http-response']
