[[observatories]]
== Observatories

Observatories are groups of experts affiliated with different institutions that curates and organize ORKG content for a specific discipline.
Observatories represent groups which are managed by <<organizations>>.
One Observatory can be managed by many organizations.
[[observatories-list]]
=== Listing Observatories

A `GET` request lists all organizations:

operation::observatory-controller-integration-test-index[snippets='curl-request,http-response']

[[observatories-create]]
=== Creating observatories

A `POST` request creates a new observatory with the given parameters.
The response will be `201 Created` when successful.
The observatory can be retrieved by following the URI in the `Location` header field.

NOTE: The response body contains the created observatory for convenience. This might be subject to change.

operation::observatories-create[snippets='request-fields,curl-request,http-response']

[[observatories-fetch]]
=== Fetching an observatory

A `GET` request provides information about a resource.

operation::observatory-controller-integration-test-fetch[snippets='curl-request,http-response']

[[observatories-edit]]
=== Editing an observatory

A `PATCH` request updates an existing observatory with the given parameters.
Only fields provided in the response, and therefore non-null, will be updated.
The response will be `204 No Content` when successful.
The updated observatory (object) can be retrieved by following the URI in the `Location` header field.

NOTE: This endpoint can only be accessed by curators.

operation::observatories-update[snippets='request-fields,curl-request,http-response']
