= RDF Integration

[[rdf]]
== RDF Dump

The ORKG provides a dump of the entire graph in RDF, the dump is in N-Triples format.

[[rdf-dump]]
=== Getting dump

WARNING: This endpoint is deprecated. Clients are advised to update, because this endpoint will be removed in the future.

Dumps cannot be created on-the-fly anymore, but can be downloaded from `/files/rdf-dumps`.
The response will be `301 Moved Permanently`, pointing to the latest version of the dump.

operation::rdf-hints-legacy-redirect-to-dump[snippets='curl-request,http-response']

[[resolvable-vocab]]
== Resolvable Vocabulary

ORKG entities in RDF format are resolvable. Each URI refers to the description of the corresponding entity in some RDF serialization.

[[vocab-resource]]
=== Resolve a resource

A `GET` request to get the description of an ORKG resource.

NOTE: a HTTP `Accept` header should be provided with one of the values from the table below. Otherwise, the request will be redirected to the frontend UI to see the HTML description page.

operation::vocab-controller-test-resource[snippets='curl-request,http-response']


[[vocab-predicate]]
=== Resolve a predicate

A `GET` request to get the description of an ORKG predicate.

NOTE: a HTTP `Accept` header should be provided with one of the values from the table below. Otherwise, the request will be redirected to the frontend UI to see the HTML description page.

operation::vocab-controller-test-predicate[snippets='curl-request,http-response']

[[vocab-class]]
=== Resolve a class

A `GET` request to get the description of an ORKG class.

NOTE: a HTTP `Accept` header should be provided with one of the values from the table below. Otherwise, the request will be redirected to the frontend UI to see the HTML description page.

operation::vocab-controller-test-clazz[snippets='curl-request,http-response']

[[vocab-accept]]
=== Allowed accept headers

This collection of HTTP `Accept` headers are allowed by the system and the corresponding serialization format.

[cols="e,m"]
.HTTP RDF serialization accept headers
[options="header"]
|=======================
|Header  |Format
|application/n-triples   | N-Triples
|application/rdf+xml    | RDF XML
|text/n3    | N3
|application/json   | JSON-LD
|application/trig    | TriG
|application/x-trig    | TriG
|application/n-quads  | N-Quads
|text/x-nquads    | N-Quads
|text/nquads  | N-Quads
|application/turtle    | Turtle
|text/turtle  | Turtle
|=======================

== RDF Hints

Resource information can be obtained from the `/api/rdf/hints` endpoint.
It supports the following request parameters:

include::{snippets}/rdf-hints-test-filter-resources/request-parameters.adoc[]

NOTE: The `type` parameter differs from the conventions used in this document.
`property` refers to <<predicates,predicates>>, `item` to <<resources,resources>>.
