[[research-fields]]
== Research Fields

Research fields are meta objects that help better classify the content within the ORKG.
The research field is essentially a <<Resources, resource>> and hence inherits all the specifications of resource.

[[research-fields-list]]
=== Listing Problems in field

A `GET` request lists all problems used within all papers under the specified research field:

operation::research-field-controller-test-get-problems-per-field[snippets='curl-request,http-response']


[[research-fields-list-papers]]
=== Listing Papers in field

A `GET` request lists all papers under the specified research field.
//TODO:A sample request and response will be added later when the uni tests have been written.

[[research-fields-list-contributors-per-field]]
=== Listing Contributors in field

A `GET` request lists all contributors under the specified research field.
//TODO:A sample request and response will be added later when the unit tests have been written.

[[research-fields-list-comparisons]]
=== Listing Comparisons in field

A `GET` request lists all comparisons under the specified research field.
//TODO:A sample request and response will be added later when the unit tests have been written.

[[research-fields-list-problems]]
=== Listing Problems in field including sub research fields

A `GET` request lists all problems used within all papers under the specified research field and sub research fields.
//TODO:A sample request and response will be added later when the unit tests have been written.

[[research-fields-list-papers-including-subfields]]
=== Listing Papers in field including sub research fields

A `GET` request lists all papers under the specified research field and sub research fields.
//TODO:A sample request and response will be added later when the unit tests have been written.

[[research-fields-list-contributors]]
=== Listing Contributors in field including sub research fields

A `GET` request lists all contributors under the entire tree of the specified research field, comparisons, papers and individual contributions.
//TODO:A sample request and response will be added later when the unit tests have been written.

[[research-fields-list-comparisons-including-subfields]]
=== Listing Comparisons in field including sub research fields

A `GET` request lists all comparisons under the specified research field and sub research fields.
//TODO:A sample request and response will be added later when the unit tests have been written.


