= Rosetta Stone Templates

Rosetta Stone Templates represent a collection of concepts in the knowledge graph and can be seen as a collection of <<Resources,resources>>, <<Literals,literals>> and <<Predicates,predicates>>.
They can be used to model the structure of statements following the rosetta stone approach.
The provided endpoints aggregate these concepts into a rosetta stone template representation.

NOTE: The following endpoints use content negotiation, meaning that the contents of the response json depend on the specified `Accept` and `Content-Type` headers of each request.

[[rosetta-stone-templates-fetch]]
== Fetching a rosetta stone template

A `GET` request provides information about a template.

operation::rosetta-stone-templates-get-single[snippets='curl-request,response-fields']

[[rosetta-stone-templates-list]]
== Listing rosetta stone templates

A `GET` request returns a <<sorting-and-pagination,paged>> list of <<rosetta-stone-templates-fetch,rosetta stone templates>>.
If no paging request parameters are provided, the default values will be used.

operation::rosetta-stone-templates-get-paged[snippets='curl-request']

The following list of request parameters are supported:

operation::rosetta-stone-templates-get-paged-with-parameters[snippets='request-parameters']
