### Register a user
POST {{server_url}}/api/auth/register
Content-Type: application/json

{
    "email": "{{username}}",
    "password": "{{password}}",
    "matching_password": "{{password}}",
    "display_name": "Example User"
}

### Authenticate via REST-API (legacy)
POST {{server_url}}/oauth/token
Authorization: Basic {{oauth_legacy_client_id}} {{oauth_legacy_client_secret}}
Content-Type: application/x-www-form-urlencoded

grant_type=password&username={{username}}&password={{password}}

> {%
    client.global.set("access_token", response.body.access_token);
%}

### Obtain tokens via OIDC (Keycloak)
POST {{auth_server_url}}/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id = {{oauth_client_id}} &
client_secret = {{oauth_client_secret}} &
username = {{username}} &
password = {{password}} &
grant_type = password

> {%
    client.global.set("access_token", response.body.access_token);
    client.global.set("refresh_token", response.body.refresh_token);
%}
>>! tokens.json

### Refresh the access token
POST {{auth_server_url}}/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id = {{oauth_client_id}} &
client_secret = {{oauth_client_secret}} &
grant_type = refresh_token &
refresh_token = {{refresh_token}}

> {%
    client.global.set("access_token", response.body.access_token);
    client.global.set("refresh_token", response.body.refresh_token);
%}
