### Create a new comparison
POST {{server_url}}/api/comparisons
Content-Type: application/vnd.orkg.comparison.v3+json
Authorization: Bearer {{access_token}}

{
    "title": "example comparison",
    "description": "comparison description",
    "research_fields": [
        "R12"
    ],
    "authors": [
        {
            "name": "Author with id",
            "id": "R70399"
        },
        {
            "name": "Author with orcid",
            "identifiers": {
                "orcid": ["0000-1111-2222-3333"]
            }
        },
        {
            "name": "Author with id and orcid",
            "id": "R6666",
            "identifiers": {
                "orcid": ["1111-2222-3333-4444"]
            }
        },
        {
            "name": "Author with homepage",
            "homepage": "http://example.org/author"
        },
        {
            "name": "Author that just has a name"
        }
    ],
    "sdgs": ["SDG_1", "SDG_2"],
    "sources": [
        {
            "id": "R1031",
            "type": "THING"
        },
        {
            "id": "R2006",
            "type": "THING"
        },
        {
            "id": "R2012",
            "type": "THING"
        },
        {
            "id": "R2101",
            "type": "THING"
        }
    ],
    "references": [
        "https://orkg.org/resources/R1000",
        "paper citation"
    ],
    "observatories": [
        "1afefdd0-5c09-4c9c-b718-2b35316b56f3"
    ],
    "organizations": [
        "edc18168-c4ee-4cb8-a98a-136f748e912e"
    ],
    "is_anonymized": false,
    "extraction_method": "MANUAL"
}

> {%
    const location = response.headers.valueOf("Location")
    const id = location.substring(location.lastIndexOf('/') + 1)
    client.global.set("comparison_id", id);
%}

### Fetch comparison table paths
GET {{server_url}}/api/comparisons/{{comparison_id}}/table-paths
Content-Type: application/vnd.orkg.comparison.v3+json

### Update comparison table contents
PUT {{server_url}}/api/comparisons/{{comparison_id}}/contents
Content-Type: application/vnd.orkg.comparison.v3+json
Authorization: Bearer {{access_token}}

{
    "selected_paths": [
        {
            "id": "P2001",
            "type": "PREDICATE",
            "children": [
                {
                    "id": "P2003",
                    "type": "PREDICATE",
                    "children": []
                },
                {
                    "id": "P2002",
                    "type": "PREDICATE",
                    "children": []
                },
                {
                    "id": "P2004",
                    "type": "PREDICATE",
                    "children": []
                },
                {
                    "id": "P21",
                    "type": "PREDICATE",
                    "children": []
                }
            ]
        },
        {
            "id": "P27",
            "type": "PREDICATE",
            "children": []
        },
        {
            "id": "P34",
            "type": "PREDICATE",
            "children": [
                {
                    "id": "P1007",
                    "type": "PREDICATE",
                    "children": [
                        {
                            "id": "P1008",
                            "type": "PREDICATE",
                            "children": []
                        },
                        {
                            "id": "P1009",
                            "type": "PREDICATE",
                            "children": []
                        }
                    ]
                },
                {
                    "id": "P1005",
                    "type": "PREDICATE",
                    "children": []
                },
                {
                    "id": "P1006",
                    "type": "PREDICATE",
                    "children": []
                }
            ]
        },
        {
            "id": "P15",
            "type": "PREDICATE",
            "children": [
                {
                    "id": "P21",
                    "type": "PREDICATE",
                    "children": [
                        {
                            "id": "P15358",
                            "type": "PREDICATE",
                            "children": []
                        },
                        {
                            "id": "P14",
                            "type": "PREDICATE",
                            "children": []
                        }
                    ]
                },
                {
                    "id": "P1002",
                    "type": "PREDICATE",
                    "children": []
                },
                {
                    "id": "P1001",
                    "type": "PREDICATE",
                    "children": [
                        {
                            "id": "P1004",
                            "type": "PREDICATE",
                            "children": []
                        },
                        {
                            "id": "P1003",
                            "type": "PREDICATE",
                            "children": []
                        }
                    ]
                },
                {
                    "id": "P1000",
                    "type": "PREDICATE",
                    "children": []
                }
            ]
        },
        {
            "id": "P32",
            "type": "PREDICATE",
            "children": [
                {
                    "id": "SAME_AS",
                    "type": "PREDICATE",
                    "children": []
                }
            ]
        },
        {
            "id": "P2000",
            "type": "PREDICATE",
            "children": []
        }
    ]
}

### Fetch comparison table contents
GET {{server_url}}/api/comparisons/{{comparison_id}}/contents
Content-Type: application/vnd.orkg.comparison.v3+json

### Update the newly created comparison
PUT {{server_url}}/api/comparisons/{{comparison_id}}
Content-Type: application/vnd.orkg.comparison.v3+json
Authorization: Bearer {{access_token}}

{
    "title": "updated comparison",
    "description": "updated comparison description",
    "research_fields": [
        "R13"
    ],
    "authors": [
        {
            "name": "Other author with id",
            "id": "R70399"
        },
        {
            "name": "Author with orcid",
            "identifiers": {
                "orcid": ["0000-1111-2222-3333"]
            }
        },
        {
            "name": "Author with id and orcid",
            "id": "R6666",
            "identifiers": {
                "orcid": ["1111-2222-3333-4444"]
            }
        },
        {
            "name": "Author with homepage",
            "homepage": "http://example.org/author"
        },
        {
            "name": "Author that just has a name"
        }
    ],
    "sdgs": ["SDG_3", "SDG_2"],
    "sources": [
        {
            "id": "R1031",
            "type": "THING"
        },
        {
            "id": "R2006",
            "type": "THING"
        },
        {
            "id": "R2012",
            "type": "THING"
        },
        {
            "id": "R2101",
            "type": "THING"
        }
    ],
    "references": [
        "other paper citation",
        "paper citation"
    ],
    "observatories": [
        "1afefdd0-5c09-4c9c-b718-2b35316b56f3"
    ],
    "organizations": [
        "edc18168-c4ee-4cb8-a98a-136f748e912e"
    ],
    "is_anonymized": true,
    "extraction_method": "AUTOMATIC"
}

### Publish the comparison
POST {{server_url}}/api/comparisons/{{comparison_id}}/publish
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "subject": "Comparison subject",
    "description": "Comparison description",
    "authors": [
        {
            "name": "Other author with id",
            "id": "R70399"
        }
    ],
    "assign_doi": false
}
