### Import class by URI
POST {{server_url}}/api/import/classes
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "ontology": "wikidata",
    "uri": "https://www.wikidata.org/entity/Q131740"
}
