= CSV Import

A CSV is a comma separated list of values.
They can be used to import data into the {orkg}.
There are three workflow stages for a CSV:

image::csv-import-flow.svg[format=svg,opts=interactive,width=100%,height=326]

////
[mermaid,format=svg,opts=interactive,width=100%]
----
stateDiagram-v2
    direction LR
    [*] --> UPLOADED
    state "Stage 1: Upload" as UploadedStage {
        UPLOADED --> VALIDATION_QUEUED : validate
    }
    state "Stage 2: Validation" as ValidationStage {
        VALIDATION_QUEUED --> VALIDATION_RUNNING
        VALIDATION_RUNNING --> VALIDATION_STOPPED
        VALIDATION_RUNNING --> VALIDATION_DONE
        VALIDATION_RUNNING --> VALIDATION_FAILED
        VALIDATION_DONE --> IMPORT_QUEUED : import
        VALIDATION_STOPPED --> VALIDATION_QUEUED
    }
    state "Stage 3: Import" as ImportStage {
        IMPORT_QUEUED --> IMPORT_RUNNING
        IMPORT_RUNNING --> IMPORT_STOPPED
        IMPORT_RUNNING --> IMPORT_DONE
        IMPORT_RUNNING --> IMPORT_FAILED
        IMPORT_STOPPED --> IMPORT_QUEUED
    }
    VALIDATION_FAILED --> [*]
    IMPORT_FAILED --> [*]
    IMPORT_DONE --> [*]
----
////

[[csvs-fetch]]
== Fetching CSVs

A `GET` request provides information about a CSV.

[NOTE]
====
1. This endpoint requires authentication.
2. Only CSVs created by the active user can be fetched.
3. Contents of a CSV need to be fetched separately. See <<csvs-data,Fetching CSV data>>.
====

operation::csvs_get-single[snippets='path-parameters,curl-request,http-response,response-fields']

[[csvs-fetch-data]]
== Fetching CSV data

A `GET` request provides information about the contents of a CSV.

operation::csvs_get-single-data[snippets='path-parameters,curl-request,http-response']

[[csvs-list]]
== Listing CSVs

A `GET` request returns a <<sorting-and-pagination,paged>> list of <<csvs-fetch,CSVs>> of the current user.
If no paging request parameters are provided, the default values will be used.

[NOTE]
====
1. This endpoint requires authentication.
2. Only CSVs created by the active user can be listed.
3. Contents of each CSV need to be fetched separately. See <<csvs-data,Fetching CSV data>>.
====

operation::csvs_get-paged[snippets='curl-request']

[[csvs-create]]
== Creating CSVs

A `POST` request creates a new CSV.
The response status will be `201 Created` when successful.
The CSV can be retrieved by following the URI in the `Location` header field.

operation::csvs_create[snippets='request-parts,curl-request,response-headers,http-response']

[[csvs-update]]
== Updating CSVs

A `PUT` request updates an existing CSV.
The response status will be `204 No Content` when successful.

[NOTE]
====
1. A CSV can only be updated as long as the import was not started yet.
2. Updating a CSV will reset the state of the CSV to `UPLOADED`.
====

operation::csvs_update[snippets='path-parameters,request-parts,curl-request,http-response']

[[csvs-validate]]
== Validating CSVs

Before a CSV can be imported, it must be valiated.
The following endpoints describe the workflow of validating a CSV.

[[csvs-validate-start]]
=== Starting CSV Validation

A `POST` request queues a new job to validate a CSV.
The response status will be `202 Accepted` when successful.

operation::csvs_start-validation[snippets='path-parameters,curl-request,http-response']

[[csvs-validate-fetch-status]]
=== Fetching CSV Validation Status

A `GET` request provides information about the validation job status.

[NOTE]
====
1. This endpoint requires authentication.
2. Only jobs started by the active user can be fetched.
====

operation::csvs_get-validation-status[snippets='path-parameters,curl-request,http-response,response-fields']

[[csvs-validate-fetch-results]]
=== Fetching CSV Validation Results

A `GET` request provides information about the validation results.

[NOTE]
====
1. This endpoint requires authentication.
2. Only jobs started by the active user can be fetched.
3. Results are only available for completed validation jobs.
4. The response status will be `400 BAD REQUEST` with response body contents of type orkg:problem:job_execution_exception, if the validation ran into an error.
====

operation::csvs_get-validation-results[snippets='path-parameters,curl-request,http-response,response-fields']

[[csvs-validate-stop]]
=== Stopping CSV Validation

A `DELETE` request stops an active CSV validation job.
The response status will be `204 No Content` when successful.

[NOTE]
====
1. This endpoint requires authentication.
2. Only jobs started by the active user can be stopped.
====

operation::csvs_stop-validation[snippets='path-parameters,curl-request,http-response']

[[csvs-import]]
== Importing CSVs

After a CSV has been validated, it can be imported.
The following endpoints describe the workflow of importing a CSV.

[[csvs-import-start]]
=== Starting a CSV Import

A `POST` request queues a new job to import a CSV.
The response status will be `202 Accepted` when successful.

operation::csvs_start-import[snippets='path-parameters,curl-request,http-response']

[[csvs-import-fetch-status]]
=== Fetching CSV Import Status

A `GET` request provides information about the import job status.

[NOTE]
====
1. This endpoint requires authentication.
2. Only jobs started by the active user can be fetched.
====

operation::csvs_get-import-status[snippets='path-parameters,curl-request,http-response,response-fields']

[[csvs-import-fetch-results]]
=== Fetching CSV Import Results

A `GET` request provides information about the import results.

[NOTE]
====
1. This endpoint requires authentication.
2. Only jobs started by the active user can be fetched.
3. Results are only available for completed imports.
4. The response status will be `400 BAD REQUEST` with response body contents of type orkg:problem:job_execution_exception, if the import ran into an error.
====

operation::csvs_get-import-results[snippets='path-parameters,curl-request,http-response,response-fields']

[[csvs-import-stop]]
=== Stopping a CSV Import

A `DELETE` request stops an active CSV import job.
The response status will be `204 No Content` when successful.

[NOTE]
====
1. This endpoint requires authentication.
2. Only jobs started by the active user can be stopped.
====

operation::csvs_stop-import[snippets='path-parameters,curl-request,http-response']

[[csvs-delete]]
== Deleting CSVs

A `DELETE` request deletes a CSV associated with the given id.
The response status will be `204 NO CONTENT` when successful.

operation::csvs_delete[snippets='path-parameters,curl-request,http-response']
