= RDF Integration

[[rdf]]
== RDF Dump

The ORKG provides a dump of the entire graph in RDF, the dump is in N-Triples format.

[[rdf-dump]]
=== Getting dump

WARNING: This endpoint is deprecated. Clients are advised to update, because this endpoint will be removed in the future.

Dumps cannot be created on-the-fly anymore, but can be downloaded from `/files/rdf-dumps`.
The response will be `301 Moved Permanently`, pointing to the latest version of the dump.

operation::rdf-hints-legacy-redirect-to-dump[snippets='curl-request,http-response']

[[rdf-dump-create]]
=== Creating Dumps

Dumps are created automatically by the system, but can also be triggered manually usng a `POST` request.

NOTE: This endpoint requires the admin role.

operation::rdf-hints-create-rdf-dump[snippets='curl-request,http-response']

[[resolvable-vocab]]
== Resolvable Vocabulary

ORKG entities in RDF format are resolvable.
Each URI refers to the description of the corresponding entity in some RDF serialization.

An RDF format media type can be provided via the `Accept` header field.
For a list of supported media types, see <<vocab-accept>> below.

[[vocab-resource]]
=== Resolve a resource

A `GET` request to get the description of an ORKG resource.

operation::rdf-vocab-resolve-resource[snippets='path-parameters,curl-request,http-response']

[[vocab-predicate]]
=== Resolve a predicate

A `GET` request to get the description of an ORKG predicate.

operation::rdf-vocab-resolve-predicate[snippets='path-parameters,curl-request,http-response']

[[vocab-class]]
=== Resolve a class

A `GET` request to get the description of an ORKG class.

operation::rdf-vocab-resolve-class[snippets='path-parameters,curl-request,http-response']

[[vocab-accept]]
=== Supported media types

Serialization to the following RDF media types is supported:

[cols="m,"]
.Supported RDF media types
[options="header"]
|===
| Media Type            | Format
| application/n-triples | N-Triples
| application/rdf+xml   | RDF XML
| text/n3               | N3
| application/json      | JSON-LD
| application/trig      | TriG
| application/x-trig    | TriG
| application/n-quads   | N-Quads
| text/x-nquads         | N-Quads
| text/nquads           | N-Quads
| application/turtle    | Turtle
| text/turtle           | Turtle
|===
